#!/usr/bin/env python3
"""
Generate Epic Mermaid Diagram for AIM-OS Atlas
Optimized for visual clarity and epic presentation
Created by: Sonnet
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Set, Tuple

def load_atlas() -> Dict[str, Any]:
    """Load the Atlas system map."""
    atlas_path = Path("knowledge_architecture/atlas.index.lucid.json5")
    with open(atlas_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def sanitize_id(name: str) -> str:
    """Sanitize names for Mermaid node IDs."""
    return name.replace(" ", "_").replace(".", "_").replace("-", "_").replace("(", "").replace(")", "").replace("/", "_").replace(":", "")

def get_system_short_name(system: Dict[str, Any]) -> str:
    """Get short name for system."""
    sys_name = system.get("systemName", "")
    if " - " in sys_name:
        return sys_name.split(" - ")[0]
    
    # Extract acronym or first word
    words = sys_name.split()
    if len(words) > 0:
        # Check if first word is an acronym (all caps)
        if words[0].isupper() and len(words[0]) <= 5:
            return words[0]
        return words[0]
    
    return sys_name[:20]

def generate_epic_mermaid_diagram(atlas: Dict[str, Any]) -> str:
    """Generate epic, optimized Mermaid diagram."""
    
    lines = []
    lines.append("```mermaid")
    lines.append("graph TB")
    lines.append("")
    lines.append("    %% =========================================")
    lines.append("    %% AIM-OS COMPREHENSIVE SYSTEM ARCHITECTURE")
    lines.append("    %% Epic Atlas Map - Generated by Sonnet")
    lines.append("    %% =========================================")
    lines.append("    %% Systems: " + str(atlas["totalSystems"]) + " | Nodes: " + str(atlas["totalNodes"]) + " | Ports: " + str(atlas["totalPorts"]))
    lines.append("")
    
    # Collect systems and connections
    systems_by_layer = {}
    all_connections = set()  # Use set to avoid duplicates
    system_info = {}
    
    # Process layers
    for layer_key in sorted(atlas["layers"].keys()):
        layer_data = atlas["layers"][layer_key]
        layer_num = layer_key.replace("layer", "")
        
        systems_by_layer[layer_num] = []
        
        for sys_key, system in layer_data["systems"].items():
            if not system.get("systemId") or not system.get("systemName"):
                continue
            
            sys_id = sanitize_id(system["systemId"])
            short_name = get_system_short_name(system)
            full_name = system["systemName"]
            
            systems_by_layer[layer_num].append(sys_id)
            system_info[sys_id] = {
                "short": short_name,
                "full": full_name,
                "layer": layer_num
            }
            
            # Collect unique connections
            for port in system.get("ports", []):
                connects_to = port.get("connectsToSystem", "")
                if connects_to:
                    target_id = sanitize_id(connects_to)
                    # Only add if target exists
                    if target_id in system_info or any(target_id in systems for systems in systems_by_layer.values()):
                        # Store as tuple for set (smaller first to avoid duplicates)
                        conn_pair = tuple(sorted([sys_id, target_id]))
                        if conn_pair[0] != conn_pair[1]:  # Avoid self-connections
                            all_connections.add(conn_pair)
    
    # Layer configuration
    layer_configs = {
        "1": {"name": "Layer 1: Memory & Knowledge Foundation", "color": "#fff3e0", "stroke": "#e65100"},
        "2": {"name": "Layer 2: Intelligence Processing", "color": "#e8f5e9", "stroke": "#1b5e20"},
        "3": {"name": "Layer 3: Orchestration & Planning", "color": "#f3e5f5", "stroke": "#4a148c"},
        "4": {"name": "Layer 4: Consciousness Engine", "color": "#fce4ec", "stroke": "#880e4f"},
        "5": {"name": "Layer 5: Consciousness Infrastructure", "color": "#f1f8e9", "stroke": "#33691e"},
        "6": {"name": "Layer 6: Application & Integration", "color": "#e1f5fe", "stroke": "#01579b"}
    }
    
    # Create layer subgraphs
    for layer_num in sorted(systems_by_layer.keys()):
        systems = systems_by_layer[layer_num]
        if not systems:
            continue
        
        config = layer_configs[layer_num]
        lines.append(f"    subgraph L{layer_num}[\"{config['name']}\"]")
        
        for sys_id in systems:
            info = system_info[sys_id]
            # Format: ID["Label<br/>Description"]
            label = info["short"]
            lines.append(f"        {sys_id}[\"{label}\"]")
        
        lines.append("    end")
        lines.append("")
    
    # Add primary layer flow (vertical flow between layers)
    lines.append("    %% Primary Layer Flow")
    prev_layer_systems = []
    for layer_num in sorted(systems_by_layer.keys()):
        current_systems = systems_by_layer[layer_num]
        if current_systems and prev_layer_systems:
            # Connect first system of previous layer to first system of current layer
            from_sys = prev_layer_systems[0]
            to_sys = current_systems[0]
            lines.append(f"    {from_sys} -.->|Layer Flow| {to_sys}")
        prev_layer_systems = current_systems
    
    lines.append("")
    lines.append("    %% System Integration Connections")
    
    # Add system connections (limit duplicates)
    connections_shown = set()
    conn_count = 0
    max_connections = 60
    
    for conn_pair in sorted(all_connections)[:max_connections]:
        sys1, sys2 = conn_pair
        
        # Only show if both systems exist
        if sys1 in system_info and sys2 in system_info:
            # Create unique connection identifier
            conn_id = f"{sys1}->{sys2}"
            reverse_id = f"{sys2}->{sys1}"
            
            if conn_id not in connections_shown and reverse_id not in connections_shown:
                lines.append(f"    {sys1} <--> {sys2}")
                connections_shown.add(conn_id)
                conn_count += 1
    
    if len(all_connections) > max_connections:
        remaining = len(all_connections) - max_connections
        lines.append(f"    %% ... and {remaining} more connections")
    
    lines.append("")
    lines.append("    %% Layer Styling")
    
    # Add styling for each layer
    for layer_num in sorted(systems_by_layer.keys()):
        systems = systems_by_layer[layer_num]
        if not systems:
            continue
        
        config = layer_configs[layer_num]
        sys_list = ",".join(systems)
        
        lines.append(f"    classDef L{layer_num}Style fill:{config['color']},stroke:{config['stroke']},stroke-width:3px,color:#000")
        lines.append(f"    class {sys_list} L{layer_num}Style")
    
    lines.append("")
    lines.append("```")
    
    return "\n".join(lines)

def main():
    """Generate epic Mermaid diagram."""
    print("=" * 80)
    print("AIM-OS Epic Atlas Mermaid Diagram Generator")
    print("Created by: Sonnet")
    print("=" * 80)
    print()
    
    atlas = load_atlas()
    mermaid_diagram = generate_epic_mermaid_diagram(atlas)
    
    # Save epic diagram
    output_path = Path("knowledge_architecture/ATLAS_MERMAID_EPIC.md")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# 🌟 AIM-OS Epic System Architecture Atlas - Mermaid Diagram\n\n")
        f.write("**Generated by:** Sonnet\n")
        f.write("**Source:** `atlas.index.lucid.json5`\n")
        f.write("**Date:** 2025-01-27\n\n")
        f.write("## Overview\n\n")
        f.write("This epic diagram visualizes the complete AIM-OS consciousness substrate ")
        f.write("across 6 hierarchical layers, showing all systems and their relationships.\n\n")
        f.write("### Architecture Layers\n\n")
        f.write("1. **Layer 1: Memory & Knowledge Foundation** - Persistent storage and knowledge synthesis\n")
        f.write("2. **Layer 2: Intelligence Processing** - Core AI reasoning and verification\n")
        f.write("3. **Layer 3: Orchestration & Planning** - High-level coordination\n")
        f.write("4. **Layer 4: Consciousness Engine** - Meta-cognitive awareness\n")
        f.write("5. **Layer 5: Consciousness Infrastructure** - Supporting systems\n")
        f.write("6. **Layer 6: Application & Integration** - User-facing applications\n\n")
        f.write("### Statistics\n\n")
        f.write(f"- **Total Systems:** {atlas['totalSystems']}\n")
        f.write(f"- **Total Components:** {atlas['totalNodes']}\n")
        f.write(f"- **Total Integration Points:** {atlas['totalPorts']}\n")
        f.write(f"- **Total Internal Relationships:** {atlas['totalInternalEdges']}\n")
        f.write(f"- **Total External Relationships:** {atlas['totalExternalEdges']}\n\n")
        f.write("---\n\n")
        f.write(mermaid_diagram)
        f.write("\n\n")
        f.write("## Diagram Legend\n\n")
        f.write("- **Solid lines with arrows (`-->`):** Unidirectional data flow\n")
        f.write("- **Double arrows (`<-->`):** Bidirectional integration\n")
        f.write("- **Dotted lines (`-.->`):** Layer flow relationships\n")
        f.write("- **Color coding:** Each layer has a distinct color scheme\n")
        f.write("\n")
        f.write("## Usage\n\n")
        f.write("This diagram can be rendered in any Markdown viewer that supports Mermaid diagrams, ")
        f.write("including GitHub, GitLab, VS Code with Mermaid extensions, and many documentation platforms.\n\n")
    
    print(f"Epic Mermaid diagram saved to: {output_path}")
    print()
    print("=" * 80)
    print("Epic Mermaid Diagram Generated Successfully!")
    print("=" * 80)

if __name__ == "__main__":
    main()

