#!/usr/bin/env python3
"""
Generate Epic Branched Atlas System Map
Shows complete hierarchical branches: Layers → Systems → Components → Subcomponents
Created by: Sonnet
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Set

def load_atlas() -> Dict[str, Any]:
    """Load the Atlas system map."""
    atlas_path = Path("knowledge_architecture/atlas.index.lucid.json5")
    with open(atlas_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def sanitize_id(name: str) -> str:
    """Sanitize names for Mermaid node IDs."""
    return name.replace(" ", "_").replace(".", "_").replace("-", "_").replace("(", "").replace(")", "").replace("/", "_").replace(":", "").lower()

def build_component_branches(system: Dict[str, Any]) -> Dict[str, Any]:
    """Build complete component branch structure."""
    
    components = {}
    edges = system.get("internalEdges", [])
    
    # Create component nodes
    for comp in system.get("internalNodes", []):
        comp_id = comp.get("id", "")
        components[comp_id] = {
            "id": comp_id,
            "name": comp.get("id", "").replace("_", " ").title(),
            "kind": comp.get("kind", "component"),
            "responsibility": comp.get("responsibility", ""),
            "children": [],
            "parents": [],
            "outgoing": [],
            "incoming": []
        }
    
    # Build relationships
    for edge in edges:
        from_comp = edge.get("from")
        to_comp = edge.get("to")
        
        if from_comp in components and to_comp in components:
            components[from_comp]["children"].append(to_comp)
            components[from_comp]["outgoing"].append({
                "to": to_comp,
                "type": edge.get("type", ""),
                "data_flow": edge.get("data_flow", "")
            })
            
            components[to_comp]["parents"].append(from_comp)
            components[to_comp]["incoming"].append({
                "from": from_comp,
                "type": edge.get("type", ""),
                "data_flow": edge.get("data_flow", "")
            })
    
    # Identify root components (no parents)
    root_components = [comp_id for comp_id, comp_data in components.items() if not comp_data["parents"]]
    
    # Build branch trees
    branches = {}
    for root_id in root_components:
        branches[root_id] = build_branch_tree(root_id, components, visited=set())
    
    return {
        "components": components,
        "branches": branches,
        "rootComponents": root_components,
        "leafComponents": [comp_id for comp_id, comp_data in components.items() if not comp_data["children"]]
    }

def build_branch_tree(comp_id: str, components: Dict[str, Any], visited: Set[str], depth: int = 0) -> Dict[str, Any]:
    """Recursively build branch tree."""
    if comp_id in visited or depth > 10:  # Prevent infinite loops
        return None
    
    visited.add(comp_id)
    comp_data = components[comp_id]
    
    branch = {
        "component": comp_id,
        "name": comp_data["name"],
        "kind": comp_data["kind"],
        "depth": depth,
        "children": []
    }
    
    for child_id in comp_data["children"]:
        child_branch = build_branch_tree(child_id, components, visited.copy(), depth + 1)
        if child_branch:
            branch["children"].append(child_branch)
    
    return branch

def generate_epic_branched_mermaid(atlas: Dict[str, Any]) -> str:
    """Generate epic Mermaid with complete branch structure."""
    
    lines = []
    lines.append("```mermaid")
    lines.append("graph TB")
    lines.append("")
    lines.append("    %% =========================================")
    lines.append("    %% AIM-OS EPIC BRANCHED SYSTEM ARCHITECTURE")
    lines.append("    %% Complete Hierarchical Branches: Layers → Systems → Components → Relationships")
    lines.append("    %% Generated by Sonnet")
    lines.append("    %% =========================================")
    lines.append("    %% Systems: " + str(atlas["totalSystems"]) + " | Components: " + str(atlas["totalNodes"]) + " | Internal Edges: " + str(atlas["totalInternalEdges"]))
    lines.append("")
    
    # Process each layer and build complete structure
    systems_with_branches = {}
    
    for layer_key in sorted(atlas["layers"].keys()):
        layer_data = atlas["layers"][layer_key]
        layer_num = layer_key.replace("layer", "")
        
        for sys_key, system in layer_data["systems"].items():
            if not system.get("systemId") or not system.get("systemName"):
                continue
            
            sys_id = sanitize_id(system["systemId"])
            sys_name = get_short_name(system["systemName"])
            
            # Build component branches
            branches = build_component_branches(system)
            systems_with_branches[sys_id] = {
                "name": sys_name,
                "full_name": system["systemName"],
                "layer": layer_num,
                "branches": branches,
                "ports": system.get("ports", []),
                "internalEdges": system.get("internalEdges", [])
            }
    
    # Layer configuration
    layer_configs = {
        "1": {"name": "Layer 1: Memory & Knowledge Foundation", "color": "#fff3e0", "stroke": "#e65100"},
        "2": {"name": "Layer 2: Intelligence Processing", "color": "#e8f5e9", "stroke": "#1b5e20"},
        "3": {"name": "Layer 3: Orchestration & Planning", "color": "#f3e5f5", "stroke": "#4a148c"},
        "4": {"name": "Layer 4: Consciousness Engine", "color": "#fce4ec", "stroke": "#880e4f"},
        "5": {"name": "Layer 5: Consciousness Infrastructure", "color": "#f1f8e9", "stroke": "#33691e"},
        "6": {"name": "Layer 6: Application & Integration", "color": "#e1f5fe", "stroke": "#01579b"}
    }
    
    # Group systems by layer
    systems_by_layer = {}
    for sys_id, sys_data in systems_with_branches.items():
        layer = sys_data["layer"]
        if layer not in systems_by_layer:
            systems_by_layer[layer] = []
        systems_by_layer[layer].append(sys_id)
    
    # Create nested structure with branches
    for layer_num in sorted(systems_by_layer.keys()):
        systems = systems_by_layer[layer_num]
        if not systems:
            continue
        
        config = layer_configs[layer_num]
        lines.append(f"    subgraph L{layer_num}[\"{config['name']}\"]")
        
        for sys_id in systems:
            sys_data = systems_with_branches[sys_id]
            branches = sys_data["branches"]
            
            lines.append(f"        subgraph {sys_id}[\"{sys_data['name']}\"]")
            
            # Add all components (showing in branch structure)
            components = branches.get("components", {})
            for comp_id, comp_data in components.items():
                comp_label = comp_data["name"][:25]
                lines.append(f"            {sys_id}_{comp_id}[\"{comp_label}\"]")
            
            lines.append("        end")
        
        lines.append("    end")
        lines.append("")
    
    # Add component-to-component connections (showing branch relationships)
    lines.append("    %% Component Branch Connections (Showing Hierarchical Flow)")
    connections_added = set()
    
    for sys_id, sys_data in systems_with_branches.items():
        edges = sys_data["internalEdges"]
        for edge in edges:
            from_comp = edge.get("from")
            to_comp = edge.get("to")
            
            if from_comp and to_comp:
                conn_key = f"{sys_id}_{from_comp}->{sys_id}_{to_comp}"
                if conn_key not in connections_added:
                    edge_type = edge.get("type", "")
                    # Use different line styles based on relationship type
                    if "creates" in edge_type.lower() or "provides" in edge_type.lower():
                        lines.append(f"    {sys_id}_{from_comp} -->|{edge_type[:20]}| {sys_id}_{to_comp}")
                    else:
                        lines.append(f"    {sys_id}_{from_comp} --> {sys_id}_{to_comp}")
                    connections_added.add(conn_key)
    
    lines.append("")
    lines.append("    %% System-to-System Integration Connections")
    
    # Add system connections
    sys_conn_added = set()
    for sys_id, sys_data in systems_with_branches.items():
        for port in sys_data["ports"]:
            connects_to = port.get("connectsToSystem", "")
            if connects_to:
                target_id = sanitize_id(connects_to)
                if target_id in systems_with_branches:
                    conn_key = f"{sys_id}->{target_id}"
                    reverse_key = f"{target_id}->{sys_id}"
                    
                    if conn_key not in sys_conn_added and reverse_key not in sys_conn_added:
                        port_id = port.get("portId", "")
                        if port.get("direction") == "bidirectional":
                            lines.append(f"    {sys_id} <-->|{port_id[:15]}| {target_id}")
                        else:
                            lines.append(f"    {sys_id} -->|{port_id[:15]}| {target_id}")
                        sys_conn_added.add(conn_key)
    
    lines.append("")
    lines.append("    %% Component-to-System Integration Points")
    
    # Show which components connect to external systems
    for sys_id, sys_data in systems_with_branches.items():
        components = sys_data["branches"].get("components", {})
        ports = sys_data["ports"]
        
        for port in ports[:5]:  # Limit to avoid clutter
            connects_to = port.get("connectsToSystem", "")
            if connects_to:
                target_id = sanitize_id(connects_to)
                
                # Find integration components
                for comp_id, comp_data in components.items():
                    comp_name_lower = comp_data["name"].lower()
                    port_id_lower = port.get("portId", "").lower()
                    
                    if (port_id_lower in comp_name_lower or 
                        "integration" in comp_name_lower or
                        "port" in comp_name_lower or
                        "interface" in comp_name_lower):
                        lines.append(f"    {sys_id}_{comp_id} -.->|{port.get('portId', '')[:15]}| {target_id}")
                        break
    
    lines.append("")
    lines.append("    %% Styling")
    
    # Style systems by layer
    for layer_num in sorted(systems_by_layer.keys()):
        systems = systems_by_layer[layer_num]
        if not systems:
            continue
        
        config = layer_configs[layer_num]
        sys_list = ",".join(systems)
        
        lines.append(f"    classDef L{layer_num}Style fill:{config['color']},stroke:{config['stroke']},stroke-width:3px,color:#000")
        lines.append(f"    class {sys_list} L{layer_num}Style")
    
    # Style components by kind
    component_kinds = {}
    for sys_id, sys_data in systems_with_branches.items():
        components = sys_data["branches"].get("components", {})
        for comp_id, comp_data in components.items():
            kind = comp_data.get("kind", "component")
            if kind not in component_kinds:
                component_kinds[kind] = []
            component_kinds[kind].append(f"{sys_id}_{comp_id}")
    
    kind_colors = {
        "core.component": "#ffcdd2",
        "storage.component": "#bbdefb",
        "pipeline.component": "#c8e6c9",
        "query.component": "#ffe0b2",
        "physics.component": "#e1bee7",
        "retrieval.component": "#dcedc8",
        "quality.component": "#f8bbd0",
        "optimization.component": "#b2dfdb",
        "semantic.component": "#fff9c4",
        "interface.component": "#f5f5f5",
        "tracking.component": "#ffccbc",
        "monitoring.component": "#d1c4e9",
        "analysis.component": "#c5cae9",
        "gating.component": "#f48fb1",
        "witness.component": "#90caf9",
        "logging.component": "#a5d6a7"
    }
    
    for kind, comp_ids in component_kinds.items():
        color = kind_colors.get(kind, "#ffffff")
        if comp_ids:
            comp_list = ",".join(comp_ids[:100])  # Include more components
            kind_style = kind.replace(".", "_")
            lines.append(f"    classDef {kind_style}Style fill:{color},stroke:#666,stroke-width:1.5px")
            lines.append(f"    class {comp_list} {kind_style}Style")
    
    lines.append("")
    lines.append("```")
    
    return "\n".join(lines)

def get_short_name(full_name: str) -> str:
    """Get short name from full name."""
    if " - " in full_name:
        return full_name.split(" - ")[0]
    words = full_name.split()
    if words and words[0].isupper() and len(words[0]) <= 5:
        return words[0]
    return words[0] if words else full_name[:20]

def main():
    """Generate epic branched Atlas."""
    print("=" * 80)
    print("AIM-OS Epic Branched Atlas Generator")
    print("Complete Hierarchical Branch Structure")
    print("Created by: Sonnet")
    print("=" * 80)
    print()
    
    atlas = load_atlas()
    mermaid_diagram = generate_epic_branched_mermaid(atlas)
    
    # Save epic branched diagram
    output_path = Path("knowledge_architecture/ATLAS_MERMAID_EPIC_BRANCHED.md")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# 🌟 AIM-OS Epic Branched System Architecture Atlas\n\n")
        f.write("**Generated by:** Sonnet\n")
        f.write("**Source:** `atlas.index.lucid.json5`\n")
        f.write("**Date:** 2025-01-27\n\n")
        f.write("## Overview\n\n")
        f.write("This **epic branched** diagram shows the **complete hierarchical structure** of AIM-OS ")
        f.write("with **ALL systems, ALL components, and ALL branch relationships**.\n\n")
        f.write("### Complete Hierarchical Structure\n\n")
        f.write("1. **Layers** → 6 hierarchical layers\n")
        f.write("2. **Systems** → 13+ systems within layers\n")
        f.write("3. **Components** → 100+ components within systems\n")
        f.write("4. **Component Branches** → Complete relationship trees showing component hierarchies\n")
        f.write("5. **Integration Points** → Component-to-system connections\n\n")
        f.write("### Statistics\n\n")
        f.write(f"- **Total Systems:** {atlas['totalSystems']}\n")
        f.write(f"- **Total Components:** {atlas['totalNodes']}\n")
        f.write(f"- **Total Integration Points:** {atlas['totalPorts']}\n")
        f.write(f"- **Total Internal Relationships:** {atlas['totalInternalEdges']}\n")
        f.write(f"- **Total External Relationships:** {atlas['totalExternalEdges']}\n\n")
        f.write("### Branch Structure\n\n")
        f.write("Each system shows:\n")
        f.write("- **Root Components:** Entry points (no parents)\n")
        f.write("- **Branch Trees:** Complete hierarchical relationships\n")
        f.write("- **Component Flow:** Data flow through component branches\n")
        f.write("- **Integration Components:** Components that handle external connections\n\n")
        f.write("---\n\n")
        f.write(mermaid_diagram)
        f.write("\n\n")
        f.write("## Diagram Features\n\n")
        f.write("### Component Branches\n\n")
        f.write("- **Hierarchical Trees:** Shows parent-child relationships between components\n")
        f.write("- **Data Flow:** Arrows show how data flows through component branches\n")
        f.write("- **Branch Labels:** Relationship types labeled on connections\n\n")
        f.write("### Integration Points\n\n")
        f.write("- **Component-to-System:** Shows which components handle external integrations\n")
        f.write("- **Port Connections:** Integration ports mapped to handling components\n")
        f.write("- **System-to-System:** External system connections with port labels\n\n")
        f.write("### Styling\n\n")
        f.write("- **Layer Colors:** Distinct colors for each of 6 layers\n")
        f.write("- **Component Colors:** Styled by component kind (core, storage, pipeline, etc.)\n")
        f.write("- **Connection Styles:** Different line styles for different relationship types\n\n")
    
    print(f"Epic branched Atlas diagram saved to: {output_path}")
    print()
    print("=" * 80)
    print("Epic Branched Atlas Generated Successfully!")
    print("=" * 80)
    print()
    print(f"Components with branches: {atlas['totalNodes']}")
    print(f"Internal relationships: {atlas['totalInternalEdges']}")
    print(f"External relationships: {atlas['totalExternalEdges']}")

if __name__ == "__main__":
    main()

