#!/usr/bin/env python3
"""
Generate Epic Mermaid Diagram for AIM-OS Atlas System Map
Creates comprehensive visual representation of entire system architecture
Created by: Sonnet
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Set
from collections import defaultdict

def load_atlas() -> Dict[str, Any]:
    """Load the Atlas system map."""
    atlas_path = Path("knowledge_architecture/atlas.index.lucid.json5")
    with open(atlas_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def sanitize_id(name: str) -> str:
    """Sanitize names for Mermaid node IDs."""
    # Remove special characters, replace spaces with underscores
    return name.replace(" ", "_").replace(".", "_").replace("-", "_").replace("(", "").replace(")", "").replace("/", "_")

def generate_mermaid_diagram(atlas: Dict[str, Any]) -> str:
    """Generate comprehensive Mermaid diagram."""
    
    lines = []
    lines.append("```mermaid")
    lines.append("graph TB")
    lines.append("")
    lines.append("    %% AIM-OS Comprehensive System Architecture Atlas")
    lines.append("    %% Generated by Sonnet from Atlas System Map")
    lines.append("    %% Total: " + str(atlas["totalSystems"]) + " systems, " + str(atlas["totalNodes"]) + " nodes, " + str(atlas["totalPorts"]) + " ports")
    lines.append("")
    
    # Collect all systems and their connections
    systems_by_layer = {}
    all_connections = []
    system_ids = {}
    
    # Process each layer
    for layer_key in sorted(atlas["layers"].keys()):
        layer_data = atlas["layers"][layer_key]
        layer_num = layer_key.replace("layer", "")
        layer_name = layer_data["layerName"]
        
        systems_by_layer[layer_num] = []
        
        # Process each system in the layer
        for sys_key, system in layer_data["systems"].items():
            if not system.get("systemId") or not system.get("systemName"):
                continue
                
            sys_id = sanitize_id(system["systemId"])
            sys_name = system["systemName"].split(" - ")[0] if " - " in system["systemName"] else system["systemName"]
            short_name = sys_name.split()[0] if sys_name.split() else sys_id
            
            systems_by_layer[layer_num].append({
                "id": sys_id,
                "name": sys_name,
                "short": short_name,
                "layer": layer_num
            })
            
            system_ids[sys_id] = {
                "name": sys_name,
                "short": short_name,
                "layer": layer_num
            }
            
            # Collect connections from ports
            for port in system.get("ports", []):
                connects_to = port.get("connectsToSystem", "")
                if connects_to:
                    target_id = sanitize_id(connects_to)
                    all_connections.append({
                        "from": sys_id,
                        "to": target_id,
                        "fromLayer": layer_num,
                        "port": port.get("portId", ""),
                        "direction": port.get("direction", "bidirectional")
                    })
    
    # Create layer subgraphs
    layer_colors = {
        "1": "#fff3e0",  # Orange - Memory
        "2": "#e8f5e9",  # Green - Intelligence
        "3": "#f3e5f5",  # Purple - Orchestration
        "4": "#fce4ec",  # Pink - Consciousness
        "5": "#f1f8e9",  # Light Green - Infrastructure
        "6": "#e1f5fe"   # Blue - Application
    }
    
    layer_strokes = {
        "1": "#e65100",
        "2": "#1b5e20",
        "3": "#4a148c",
        "4": "#880e4f",
        "5": "#33691e",
        "6": "#01579b"
    }
    
    # Create subgraphs for each layer
    for layer_num in sorted(systems_by_layer.keys()):
        layer_name = atlas["layers"][f"layer{layer_num}"]["layerName"]
        systems = systems_by_layer[layer_num]
        
        if not systems:
            continue
            
        lines.append(f"    subgraph L{layer_num}[\"{layer_name}\"]")
        
        # Add systems as nodes
        for sys in systems:
            # Format: ID["Label"]
            label = sys["short"]
            lines.append(f"        {sys['id']}[\"{label}\"]")
        
        lines.append("    end")
        lines.append("")
    
    # Add connections (only between different systems, avoid duplicates)
    connections_added = set()
    
    # First, add primary layer connections (layer 1 -> 2 -> 3 -> 4 -> 5 -> 6)
    for i in range(1, 6):
        layer1_systems = systems_by_layer.get(str(i), [])
        layer2_systems = systems_by_layer.get(str(i+1), [])
        
        if layer1_systems and layer2_systems:
            # Connect first system of layer1 to first system of layer2 as layer connection
            if layer1_systems and layer2_systems:
                from_sys = layer1_systems[0]["id"]
                to_sys = layer2_systems[0]["id"]
                conn_key = f"{from_sys}->{to_sys}"
                if conn_key not in connections_added:
                    lines.append(f"    {from_sys} -.->|Layer {i}→{i+1}| {to_sys}")
                    connections_added.add(conn_key)
    
    # Add specific system connections from ports
    lines.append("")
    lines.append("    %% System Integration Connections")
    
    # Group connections by type to reduce clutter
    connection_groups = defaultdict(list)
    
    for conn in all_connections:
        from_id = conn["from"]
        to_id = conn["to"]
        
        # Only add if both systems exist in our map
        if from_id in system_ids and to_id in system_ids:
            conn_key = f"{from_id}->{to_id}"
            if conn_key not in connections_added:
                connection_groups[conn_key].append(conn)
                connections_added.add(conn_key)
    
    # Add connections (limit to avoid diagram clutter)
    conn_count = 0
    max_connections = 50  # Limit to keep diagram readable
    
    for conn_key, conns in list(connection_groups.items())[:max_connections]:
        conn = conns[0]  # Use first connection as representative
        from_id = conn["from"]
        to_id = conn["to"]
        
        # Use different arrow styles based on direction
        if conn["direction"] == "bidirectional":
            lines.append(f"    {from_id} <--> {to_id}")
        elif conn["direction"] == "outbound":
            lines.append(f"    {from_id} --> {to_id}")
        else:
            lines.append(f"    {from_id} --> {to_id}")
        
        conn_count += 1
    
    if len(connection_groups) > max_connections:
        lines.append(f"    %% ... and {len(connection_groups) - max_connections} more connections")
    
    lines.append("")
    lines.append("    %% Styling")
    
    # Add class definitions for each layer
    for layer_num in sorted(systems_by_layer.keys()):
        systems = systems_by_layer[layer_num]
        if not systems:
            continue
            
        sys_ids = ",".join([sys["id"] for sys in systems])
        color = layer_colors[layer_num]
        stroke = layer_strokes[layer_num]
        
        lines.append(f"    classDef layer{layer_num} fill:{color},stroke:{stroke},stroke-width:2px,color:#000")
        lines.append(f"    class {sys_ids} layer{layer_num}")
    
    lines.append("")
    lines.append("```")
    
    return "\n".join(lines)

def generate_detailed_mermaid_diagram(atlas: Dict[str, Any]) -> str:
    """Generate detailed Mermaid diagram with components."""
    
    lines = []
    lines.append("```mermaid")
    lines.append("graph TB")
    lines.append("")
    lines.append("    %% AIM-OS Detailed System Architecture with Components")
    lines.append("    %% Generated by Sonnet - Detailed View")
    lines.append("")
    
    # Process each layer
    for layer_key in sorted(atlas["layers"].keys()):
        layer_data = atlas["layers"][layer_key]
        layer_num = layer_key.replace("layer", "")
        layer_name = layer_data["layerName"]
        
        lines.append(f"    subgraph L{layer_num}[\"{layer_name}\"]")
        
        # Process each system
        for sys_key, system in layer_data["systems"].items():
            if not system.get("systemId") or not system.get("systemName"):
                continue
                
            sys_id = sanitize_id(system["systemId"])
            sys_name = system["systemName"].split(" - ")[0] if " - " in system["systemName"] else system["systemName"]
            
            lines.append(f"        subgraph {sys_id}[\"{sys_name}\"]")
            
            # Add key components (limit to 3-5 most important)
            components = system.get("internalNodes", [])[:5]
            for comp in components:
                comp_id = sanitize_id(comp.get("id", ""))
                comp_name = comp.get("id", "").replace("_", " ").title()
                if comp_id:
                    lines.append(f"            {sys_id}_{comp_id}[\"{comp_name}\"]")
            
            lines.append("        end")
        
        lines.append("    end")
        lines.append("")
    
    lines.append("```")
    
    return "\n".join(lines)

def main():
    """Generate Mermaid diagrams."""
    print("=" * 80)
    print("AIM-OS Atlas Mermaid Diagram Generator")
    print("Created by: Sonnet")
    print("=" * 80)
    print()
    
    atlas = load_atlas()
    
    # Generate comprehensive diagram
    mermaid_diagram = generate_mermaid_diagram(atlas)
    
    # Save comprehensive diagram
    output_path = Path("knowledge_architecture/ATLAS_MERMAID_DIAGRAM.md")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# AIM-OS Comprehensive System Architecture - Mermaid Diagram\n\n")
        f.write("**Generated by:** Sonnet\n")
        f.write("**Source:** `atlas.index.lucid.json5`\n")
        f.write("**Date:** 2025-01-27\n\n")
        f.write("This diagram shows the complete AIM-OS system architecture across 6 layers, ")
        f.write("with all systems and their relationships.\n\n")
        f.write(mermaid_diagram)
        f.write("\n\n")
        f.write("## Statistics\n\n")
        f.write(f"- **Total Systems:** {atlas['totalSystems']}\n")
        f.write(f"- **Total Nodes:** {atlas['totalNodes']}\n")
        f.write(f"- **Total Ports:** {atlas['totalPorts']}\n")
        f.write(f"- **Total Internal Edges:** {atlas['totalInternalEdges']}\n")
        f.write(f"- **Total External Edges:** {atlas['totalExternalEdges']}\n\n")
    
    print(f"Comprehensive Mermaid diagram saved to: {output_path}")
    
    # Generate detailed diagram with components
    detailed_diagram = generate_detailed_mermaid_diagram(atlas)
    
    detailed_path = Path("knowledge_architecture/ATLAS_MERMAID_DIAGRAM_DETAILED.md")
    with open(detailed_path, 'w', encoding='utf-8') as f:
        f.write("# AIM-OS Detailed System Architecture - Mermaid Diagram (With Components)\n\n")
        f.write("**Generated by:** Sonnet\n")
        f.write("**Source:** `atlas.index.lucid.json5`\n")
        f.write("**Date:** 2025-01-27\n\n")
        f.write("This diagram shows systems with their key internal components.\n\n")
        f.write(detailed_diagram)
        f.write("\n\n")
    
    print(f"Detailed Mermaid diagram saved to: {detailed_path}")
    print()
    print("=" * 80)
    print("Mermaid Diagrams Generated Successfully!")
    print("=" * 80)

if __name__ == "__main__":
    main()

