#!/usr/bin/env python3
"""
Generate Ultra-Complex AIM-OS Atlas System Map
Includes ALL systems, components, subcomponents, and hierarchical relationships
Created by: Sonnet
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Set, Tuple

def load_atlas() -> Dict[str, Any]:
    """Load the Atlas system map."""
    atlas_path = Path("knowledge_architecture/atlas.index.lucid.json5")
    with open(atlas_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def sanitize_id(name: str) -> str:
    """Sanitize names for Mermaid node IDs."""
    return name.replace(" ", "_").replace(".", "_").replace("-", "_").replace("(", "").replace(")", "").replace("/", "_").replace(":", "").lower()

def get_short_name(full_name: str) -> str:
    """Get short name from full name."""
    if " - " in full_name:
        return full_name.split(" - ")[0]
    words = full_name.split()
    if words and words[0].isupper() and len(words[0]) <= 5:
        return words[0]
    return words[0] if words else full_name[:15]

def generate_ultra_complex_mermaid(atlas: Dict[str, Any]) -> str:
    """Generate ultra-complex Mermaid with all components nested."""
    
    lines = []
    lines.append("```mermaid")
    lines.append("graph TB")
    lines.append("")
    lines.append("    %% =========================================")
    lines.append("    %% AIM-OS ULTRA-COMPLEX SYSTEM ARCHITECTURE")
    lines.append("    %% Complete Hierarchical Map with ALL Components")
    lines.append("    %% Generated by Sonnet")
    lines.append("    %% =========================================")
    lines.append("    %% Systems: " + str(atlas["totalSystems"]) + " | Components: " + str(atlas["totalNodes"]) + " | Ports: " + str(atlas["totalPorts"]))
    lines.append("")
    
    # Collect all systems with their components
    systems_data = {}
    component_connections = []
    system_connections = []
    
    # Process each layer
    for layer_key in sorted(atlas["layers"].keys()):
        layer_data = atlas["layers"][layer_key]
        layer_num = layer_key.replace("layer", "")
        
        for sys_key, system in layer_data["systems"].items():
            if not system.get("systemId") or not system.get("systemName"):
                continue
            
            sys_id = sanitize_id(system["systemId"])
            sys_name = get_short_name(system["systemName"])
            
            # Collect components
            components = []
            for comp in system.get("internalNodes", []):
                comp_id = sanitize_id(comp.get("id", ""))
                comp_name = comp.get("id", "").replace("_", " ").title()
                comp_kind = comp.get("kind", "component")
                
                if comp_id:
                    components.append({
                        "id": f"{sys_id}_{comp_id}",
                        "name": comp_name,
                        "kind": comp_kind,
                        "sys_id": sys_id
                    })
            
            # Collect internal edges (component-to-component)
            for edge in system.get("internalEdges", []):
                from_comp = sanitize_id(edge.get("from", ""))
                to_comp = sanitize_id(edge.get("to", ""))
                
                if from_comp and to_comp:
                    component_connections.append({
                        "from": f"{sys_id}_{from_comp}",
                        "to": f"{sys_id}_{to_comp}",
                        "type": edge.get("type", ""),
                        "system": sys_id
                    })
            
            # Collect external edges (system-to-system)
            for port in system.get("ports", []):
                connects_to = port.get("connectsToSystem", "")
                if connects_to:
                    target_id = sanitize_id(connects_to)
                    system_connections.append({
                        "from": sys_id,
                        "to": target_id,
                        "port": port.get("portId", ""),
                        "direction": port.get("direction", "bidirectional")
                    })
            
            systems_data[sys_id] = {
                "name": sys_name,
                "full_name": system["systemName"],
                "layer": layer_num,
                "components": components
            }
    
    # Layer configuration
    layer_configs = {
        "1": {"name": "Layer 1: Memory & Knowledge Foundation", "color": "#fff3e0", "stroke": "#e65100"},
        "2": {"name": "Layer 2: Intelligence Processing", "color": "#e8f5e9", "stroke": "#1b5e20"},
        "3": {"name": "Layer 3: Orchestration & Planning", "color": "#f3e5f5", "stroke": "#4a148c"},
        "4": {"name": "Layer 4: Consciousness Engine", "color": "#fce4ec", "stroke": "#880e4f"},
        "5": {"name": "Layer 5: Consciousness Infrastructure", "color": "#f1f8e9", "stroke": "#33691e"},
        "6": {"name": "Layer 6: Application & Integration", "color": "#e1f5fe", "stroke": "#01579b"}
    }
    
    # Group systems by layer
    systems_by_layer = {}
    for sys_id, sys_data in systems_data.items():
        layer = sys_data["layer"]
        if layer not in systems_by_layer:
            systems_by_layer[layer] = []
        systems_by_layer[layer].append(sys_id)
    
    # Create nested layer/system/component structure
    for layer_num in sorted(systems_by_layer.keys()):
        systems = systems_by_layer[layer_num]
        if not systems:
            continue
        
        config = layer_configs[layer_num]
        lines.append(f"    subgraph L{layer_num}[\"{config['name']}\"]")
        
        # Create subgraph for each system with its components
        for sys_id in systems:
            sys_data = systems_data[sys_id]
            components = sys_data["components"]
            
            # System subgraph
            lines.append(f"        subgraph {sys_id}[\"{sys_data['name']}\"]")
            
            # Add all components
            for comp in components:
                comp_label = comp["name"][:20]  # Truncate for readability
                lines.append(f"            {comp['id']}[\"{comp_label}\"]")
            
            lines.append("        end")
        
        lines.append("    end")
        lines.append("")
    
    # Add component-to-component connections (within systems)
    lines.append("    %% Component-to-Component Connections (Internal)")
    connections_added = set()
    
    for conn in component_connections:
        conn_key = f"{conn['from']}->{conn['to']}"
        if conn_key not in connections_added:
            lines.append(f"    {conn['from']} --> {conn['to']}")
            connections_added.add(conn_key)
    
    lines.append("")
    lines.append("    %% System-to-System Connections (External)")
    
    # Add system-to-system connections
    sys_conn_added = set()
    for conn in system_connections:
        # Only add if both systems exist
        if conn["from"] in systems_data and conn["to"] in systems_data:
            conn_key = f"{conn['from']}->{conn['to']}"
            reverse_key = f"{conn['to']}->{conn['from']}"
            
            if conn_key not in sys_conn_added and reverse_key not in sys_conn_added:
                if conn["direction"] == "bidirectional":
                    lines.append(f"    {conn['from']} <--> {conn['to']}")
                else:
                    lines.append(f"    {conn['from']} --> {conn['to']}")
                sys_conn_added.add(conn_key)
    
    lines.append("")
    lines.append("    %% Component-to-System Connections (Key Integration Points)")
    
    # Add key component-to-system connections (components that interface with other systems)
    # This shows which components handle external integrations
    key_integration_components = []
    for sys_id, sys_data in systems_data.items():
        components = sys_data["components"]
        for comp in components:
            # Check if component name suggests it handles integrations
            comp_name_lower = comp["name"].lower()
            if any(keyword in comp_name_lower for keyword in ["integration", "port", "interface", "api", "gateway", "connector"]):
                key_integration_components.append({
                    "component": comp["id"],
                    "system": sys_id
                })
    
    # Connect integration components to their target systems (based on ports)
    for conn in system_connections[:30]:  # Limit to avoid clutter
        from_sys = conn["from"]
        to_sys = conn["to"]
        
        if from_sys in systems_data:
            # Find integration component in source system
            for comp in systems_data[from_sys]["components"]:
                comp_name_lower = comp["name"].lower()
                if any(keyword in comp_name_lower for keyword in ["integration", "port", "interface"]):
                    # Connect component to target system
                    lines.append(f"    {comp['id']} -.->|integrates| {to_sys}")
                    break
    
    lines.append("")
    lines.append("    %% Styling")
    
    # Style components by kind
    component_kinds = {}
    for sys_id, sys_data in systems_data.items():
        for comp in sys_data["components"]:
            kind = comp["kind"]
            if kind not in component_kinds:
                component_kinds[kind] = []
            component_kinds[kind].append(comp["id"])
    
    # Style systems by layer
    for layer_num in sorted(systems_by_layer.keys()):
        systems = systems_by_layer[layer_num]
        if not systems:
            continue
        
        config = layer_configs[layer_num]
        sys_list = ",".join(systems)
        
        lines.append(f"    classDef L{layer_num}Style fill:{config['color']},stroke:{config['stroke']},stroke-width:3px,color:#000")
        lines.append(f"    class {sys_list} L{layer_num}Style")
    
    # Style components by kind
    kind_colors = {
        "core.component": "#ffebee",
        "storage.component": "#e3f2fd",
        "pipeline.component": "#f1f8e9",
        "query.component": "#fff3e0",
        "physics.component": "#f3e5f5",
        "retrieval.component": "#e8f5e9",
        "quality.component": "#fce4ec",
        "optimization.component": "#e0f2f1",
        "semantic.component": "#fff9c4",
        "interface.component": "#f5f5f5"
    }
    
    for kind, comp_ids in component_kinds.items():
        color = kind_colors.get(kind, "#ffffff")
        comp_list = ",".join(comp_ids[:50])  # Limit styling
        if comp_list:
            lines.append(f"    classDef {kind.replace('.', '_')}Style fill:{color},stroke:#666,stroke-width:1px")
            lines.append(f"    class {comp_list} {kind.replace('.', '_')}Style")
    
    lines.append("")
    lines.append("```")
    
    return "\n".join(lines)

def main():
    """Generate ultra-complex Atlas with components."""
    print("=" * 80)
    print("AIM-OS Ultra-Complex Atlas Generator (With All Components)")
    print("Created by: Sonnet")
    print("=" * 80)
    print()
    
    atlas = load_atlas()
    mermaid_diagram = generate_ultra_complex_mermaid(atlas)
    
    # Save ultra-complex diagram
    output_path = Path("knowledge_architecture/ATLAS_MERMAID_ULTRA_COMPLEX.md")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# 🌟 AIM-OS Ultra-Complex System Architecture Atlas\n\n")
        f.write("**Generated by:** Sonnet\n")
        f.write("**Source:** `atlas.index.lucid.json5`\n")
        f.write("**Date:** 2025-01-27\n\n")
        f.write("## Overview\n\n")
        f.write("This **ultra-complex** diagram shows the complete AIM-OS architecture with ")
        f.write("**ALL systems, ALL components, and ALL relationships** in a hierarchical nested structure.\n\n")
        f.write("### Hierarchical Structure\n\n")
        f.write("1. **Layers** (6 hierarchical layers)\n")
        f.write("2. **Systems** (13+ systems)\n")
        f.write("3. **Components** (100+ components within systems)\n")
        f.write("4. **Connections** (component-to-component, system-to-system, integration points)\n\n")
        f.write("### Statistics\n\n")
        f.write(f"- **Total Systems:** {atlas['totalSystems']}\n")
        f.write(f"- **Total Components:** {atlas['totalNodes']}\n")
        f.write(f"- **Total Integration Points:** {atlas['totalPorts']}\n")
        f.write(f"- **Total Internal Relationships:** {atlas['totalInternalEdges']}\n")
        f.write(f"- **Total External Relationships:** {atlas['totalExternalEdges']}\n\n")
        f.write("### Diagram Structure\n\n")
        f.write("- **Nested Subgraphs:** Layers → Systems → Components\n")
        f.write("- **Component Connections:** Shows internal component relationships\n")
        f.write("- **System Connections:** Shows external system integrations\n")
        f.write("- **Integration Points:** Key components that handle external connections\n\n")
        f.write("---\n\n")
        f.write(mermaid_diagram)
        f.write("\n\n")
        f.write("## Diagram Legend\n\n")
        f.write("- **Solid arrows (`-->`):** Component-to-component flow within systems\n")
        f.write("- **Double arrows (`<-->`):** Bidirectional system integration\n")
        f.write("- **Dotted arrows (`-.->`):** Component-to-system integration points\n")
        f.write("- **Color coding:**\n")
        f.write("  - Layer colors: Distinct colors for each of 6 layers\n")
        f.write("  - Component colors: Styled by component kind (core, storage, pipeline, etc.)\n\n")
        f.write("## Usage\n\n")
        f.write("This ultra-complex diagram provides complete visibility into the AIM-OS architecture. ")
        f.write("Use it to understand:\n\n")
        f.write("- System internal structure (components within each system)\n")
        f.write("- Component relationships (how components interact)\n")
        f.write("- System integrations (how systems connect)\n")
        f.write("- Integration points (which components handle external connections)\n\n")
    
    print(f"Ultra-complex Atlas diagram saved to: {output_path}")
    print()
    print("=" * 80)
    print("Ultra-Complex Atlas Generated Successfully!")
    print("=" * 80)
    print()
    print(f"Total Components Visualized: {atlas['totalNodes']}")
    print(f"Total Internal Connections: {atlas['totalInternalEdges']}")
    print(f"Total External Connections: {atlas['totalExternalEdges']}")

if __name__ == "__main__":
    main()

