#!/usr/bin/env python3
"""
Context Analysis Engine - Analyze context and generate context profiles
Part of Daemon/RAG System Implementation

Following A-H Protocol and DEL methodology from ChatGPT journal
"""

from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass
from enum import Enum
import time
import json
import re
from datetime import datetime

class ContextType(Enum):
    """Context types for classification."""
    MEMORY_OPERATION = "memory_operation"
    PLANNING = "planning"
    TRACKING = "tracking"
    SYNTHESIS = "synthesis"
    SAFETY = "safety"
    MONITORING = "monitoring"
    TIMELINE = "timeline"
    LEARNING = "learning"
    COLLABORATION = "collaboration"
    AUTONOMOUS = "autonomous"
    RESEARCH = "research"
    DEVELOPMENT = "development"

class ComplexityLevel(Enum):
    """Complexity levels for context analysis."""
    TRIVIAL = 0.0
    LOW = 0.25
    MEDIUM = 0.5
    HIGH = 0.75
    CRITICAL = 1.0

@dataclass
class ContextProfile:
    """Context profile generated by analysis engine."""
    # Basic Information
    context_id: str
    timestamp: float
    context_type: ContextType
    complexity: ComplexityLevel
    
    # Analysis Results
    task_classification: str
    intent_inference: str
    resource_requirements: Dict[str, Any]
    constraints: List[str]
    
    # Tool Requirements
    required_capabilities: List[str]
    preferred_categories: List[str]
    performance_requirements: Dict[str, int]
    security_requirements: str
    
    # Context Quality
    confidence_score: float
    completeness_score: float
    clarity_score: float
    
    # Metadata
    analysis_duration_ms: float
    analysis_version: str = "1.0.0"

class ContextParser:
    """
    Parse user input and environment data.
    
    SpecBlock:
    - responsibility: "Parse user input and environment data"
    - must_never: "Miss critical context information", "Parse incorrectly"
    - performance_budget: "10ms average, 25ms maximum"
    - security_level: "high"
    """
    
    def __init__(self):
        self.patterns = {
            'memory_operation': [
                r'\b(store|retrieve|memory|remember|forget)\b',
                r'\b(learn|learning|knowledge)\b'
            ],
            'planning': [
                r'\b(plan|create|design|build|implement)\b',
                r'\b(strategy|approach|methodology)\b'
            ],
            'tracking': [
                r'\b(track|monitor|follow|progress)\b',
                r'\b(confidence|provenance|quality)\b'
            ],
            'synthesis': [
                r'\b(synthesize|combine|integrate|merge)\b',
                r'\b(analyze|understand|comprehend)\b'
            ],
            'safety': [
                r'\b(safety|security|protect|secure)\b',
                r'\b(invariant|integrity|validation)\b'
            ],
            'autonomous': [
                r'\b(autonomous|self|automatic|independent)\b',
                r'\b(proceed|continue|execute)\b'
            ]
        }
    
    def parse_user_input(self, user_input: str) -> Dict[str, Any]:
        """Parse user input for context clues."""
        parsed = {
            'raw_input': user_input,
            'detected_patterns': [],
            'keywords': [],
            'intent_indicators': []
        }
        
        # Extract keywords
        words = re.findall(r'\b\w+\b', user_input.lower())
        parsed['keywords'] = words
        
        # Detect patterns
        for context_type, patterns in self.patterns.items():
            for pattern in patterns:
                if re.search(pattern, user_input, re.IGNORECASE):
                    parsed['detected_patterns'].append(context_type)
        
        # Detect intent indicators
        intent_indicators = [
            'help', 'need', 'want', 'should', 'must', 'can', 'will',
            'create', 'build', 'implement', 'fix', 'solve', 'improve'
        ]
        parsed['intent_indicators'] = [word for word in words if word in intent_indicators]
        
        return parsed
    
    def parse_environment_data(self, environment: Dict[str, Any]) -> Dict[str, Any]:
        """Parse environment data for context."""
        parsed = {
            'session_info': environment.get('session_info', {}),
            'system_state': environment.get('system_state', {}),
            'user_preferences': environment.get('user_preferences', {}),
            'available_resources': environment.get('available_resources', {}),
            'constraints': environment.get('constraints', [])
        }
        return parsed

class TaskClassifier:
    """
    Classify task type and complexity.
    
    SpecBlock:
    - responsibility: "Classify task type and complexity"
    - must_never: "Misclassify critical tasks", "Underestimate complexity"
    - performance_budget: "15ms average, 30ms maximum"
    - security_level: "high"
    """
    
    def __init__(self):
        self.task_patterns = {
            'memory_operation': {
                'keywords': ['memory', 'store', 'retrieve', 'learn', 'remember'],
                'complexity_factors': ['large_data', 'complex_query', 'multiple_sources']
            },
            'planning': {
                'keywords': ['plan', 'create', 'design', 'strategy', 'approach'],
                'complexity_factors': ['multi_step', 'dependencies', 'uncertainty']
            },
            'tracking': {
                'keywords': ['track', 'monitor', 'follow', 'progress', 'confidence'],
                'complexity_factors': ['real_time', 'multiple_metrics', 'alerting']
            },
            'synthesis': {
                'keywords': ['synthesize', 'combine', 'integrate', 'analyze'],
                'complexity_factors': ['multiple_sources', 'complex_logic', 'pattern_recognition']
            },
            'safety': {
                'keywords': ['safety', 'security', 'protect', 'validate'],
                'complexity_factors': ['critical_system', 'real_time', 'high_stakes']
            },
            'autonomous': {
                'keywords': ['autonomous', 'self', 'automatic', 'independent'],
                'complexity_factors': ['decision_making', 'learning', 'adaptation']
            }
        }
    
    def classify_task(self, parsed_input: Dict[str, Any], environment: Dict[str, Any]) -> Tuple[str, float]:
        """Classify task type and complexity."""
        detected_patterns = parsed_input.get('detected_patterns', [])
        keywords = parsed_input.get('keywords', [])
        
        # Find best matching task type
        best_match = None
        best_score = 0.0
        
        for task_type, config in self.task_patterns.items():
            score = 0.0
            
            # Check keyword matches
            keyword_matches = sum(1 for keyword in keywords if keyword in config['keywords'])
            score += keyword_matches * 0.3
            
            # Check pattern matches
            if task_type in detected_patterns:
                score += 0.4
            
            # Check complexity factors
            complexity_factors = self._assess_complexity_factors(environment, config['complexity_factors'])
            score += complexity_factors * 0.3
            
            if score > best_score:
                best_score = score
                best_match = task_type
        
        # Calculate complexity level
        complexity = self._calculate_complexity(parsed_input, environment, best_match)
        
        return best_match or 'general', complexity
    
    def _assess_complexity_factors(self, environment: Dict[str, Any], factors: List[str]) -> float:
        """Assess complexity factors from environment."""
        complexity_score = 0.0
        
        for factor in factors:
            if factor == 'large_data' and environment.get('data_size', 0) > 1000:
                complexity_score += 0.2
            elif factor == 'complex_query' and environment.get('query_complexity', 0) > 0.7:
                complexity_score += 0.2
            elif factor == 'multiple_sources' and environment.get('source_count', 0) > 3:
                complexity_score += 0.2
            elif factor == 'multi_step' and environment.get('step_count', 0) > 5:
                complexity_score += 0.2
            elif factor == 'dependencies' and environment.get('dependency_count', 0) > 3:
                complexity_score += 0.2
            elif factor == 'uncertainty' and environment.get('uncertainty_level', 0) > 0.5:
                complexity_score += 0.2
            elif factor == 'real_time' and environment.get('real_time_required', False):
                complexity_score += 0.2
            elif factor == 'multiple_metrics' and environment.get('metric_count', 0) > 5:
                complexity_score += 0.2
            elif factor == 'alerting' and environment.get('alerting_required', False):
                complexity_score += 0.2
            elif factor == 'complex_logic' and environment.get('logic_complexity', 0) > 0.7:
                complexity_score += 0.2
            elif factor == 'pattern_recognition' and environment.get('pattern_recognition_required', False):
                complexity_score += 0.2
            elif factor == 'critical_system' and environment.get('critical_system', False):
                complexity_score += 0.2
            elif factor == 'high_stakes' and environment.get('high_stakes', False):
                complexity_score += 0.2
            elif factor == 'decision_making' and environment.get('decision_making_required', False):
                complexity_score += 0.2
            elif factor == 'learning' and environment.get('learning_required', False):
                complexity_score += 0.2
            elif factor == 'adaptation' and environment.get('adaptation_required', False):
                complexity_score += 0.2
        
        return min(complexity_score, 1.0)
    
    def _calculate_complexity(self, parsed_input: Dict[str, Any], environment: Dict[str, Any], task_type: str) -> float:
        """Calculate complexity level for the task."""
        base_complexity = 0.3  # Base complexity for any task
        
        # Add complexity based on input length and complexity
        input_length = len(parsed_input.get('raw_input', ''))
        if input_length > 1000:
            base_complexity += 0.2
        elif input_length > 500:
            base_complexity += 0.1
        
        # Add complexity based on detected patterns
        pattern_count = len(parsed_input.get('detected_patterns', []))
        base_complexity += pattern_count * 0.1
        
        # Add complexity based on intent indicators
        intent_count = len(parsed_input.get('intent_indicators', []))
        base_complexity += intent_count * 0.05
        
        # Add complexity based on environment factors
        if environment.get('real_time_required', False):
            base_complexity += 0.2
        if environment.get('high_stakes', False):
            base_complexity += 0.2
        if environment.get('critical_system', False):
            base_complexity += 0.2
        
        return min(base_complexity, 1.0)

class IntentInferencer:
    """
    Infer user intent and goals.
    
    SpecBlock:
    - responsibility: "Infer user intent and goals"
    - must_never: "Misinterpret user intent", "Make assumptions without evidence"
    - performance_budget: "20ms average, 40ms maximum"
    - security_level: "high"
    """
    
    def __init__(self):
        self.intent_patterns = {
            'create': ['create', 'build', 'make', 'generate', 'develop'],
            'modify': ['modify', 'change', 'update', 'edit', 'adjust'],
            'analyze': ['analyze', 'examine', 'investigate', 'study', 'review'],
            'solve': ['solve', 'fix', 'resolve', 'address', 'handle'],
            'learn': ['learn', 'understand', 'comprehend', 'discover', 'find'],
            'optimize': ['optimize', 'improve', 'enhance', 'better', 'upgrade'],
            'monitor': ['monitor', 'watch', 'track', 'follow', 'observe'],
            'synthesize': ['synthesize', 'combine', 'integrate', 'merge', 'unify']
        }
    
    def infer_intent(self, parsed_input: Dict[str, Any], task_type: str) -> str:
        """Infer user intent from parsed input."""
        keywords = parsed_input.get('keywords', [])
        intent_scores = {}
        
        for intent, patterns in self.intent_patterns.items():
            score = sum(1 for keyword in keywords if keyword in patterns)
            intent_scores[intent] = score
        
        # Find highest scoring intent
        best_intent = max(intent_scores, key=intent_scores.get) if intent_scores else 'general'
        
        # Adjust based on task type
        if task_type == 'memory_operation' and best_intent == 'create':
            return 'store_memory'
        elif task_type == 'memory_operation' and best_intent == 'learn':
            return 'retrieve_memory'
        elif task_type == 'planning' and best_intent == 'create':
            return 'create_plan'
        elif task_type == 'tracking' and best_intent == 'monitor':
            return 'track_progress'
        elif task_type == 'synthesis' and best_intent == 'synthesize':
            return 'synthesize_knowledge'
        
        return best_intent

class ResourceAssessor:
    """
    Assess available resources and constraints.
    
    SpecBlock:
    - responsibility: "Assess available resources and constraints"
    - must_never: "Overestimate available resources", "Ignore critical constraints"
    - performance_budget: "10ms average, 20ms maximum"
    - security_level: "medium"
    """
    
    def assess_resources(self, environment: Dict[str, Any]) -> Dict[str, Any]:
        """Assess available resources and constraints."""
        resources = {
            'memory_available': environment.get('memory_available', 1000),
            'cpu_available': environment.get('cpu_available', 100),
            'network_available': environment.get('network_available', True),
            'storage_available': environment.get('storage_available', 10000),
            'time_available': environment.get('time_available', 300),
            'security_level': environment.get('security_level', 'medium'),
            'constraints': environment.get('constraints', [])
        }
        return resources

class ContextValidator:
    """
    Validate context accuracy and completeness.
    
    SpecBlock:
    - responsibility: "Validate context accuracy and completeness"
    - must_never: "Accept incomplete context", "Validate incorrect information"
    - performance_budget: "5ms average, 10ms maximum"
    - security_level: "high"
    """
    
    def validate_context(self, context_profile: ContextProfile) -> Tuple[bool, List[str]]:
        """Validate context profile for accuracy and completeness."""
        issues = []
        
        # Check required fields
        if not context_profile.context_id:
            issues.append("Missing context_id")
        if not context_profile.context_type:
            issues.append("Missing context_type")
        if context_profile.complexity is None:
            issues.append("Missing complexity")
        if not context_profile.task_classification:
            issues.append("Missing task_classification")
        if not context_profile.intent_inference:
            issues.append("Missing intent_inference")
        
        # Check confidence scores
        if context_profile.confidence_score < 0.0 or context_profile.confidence_score > 1.0:
            issues.append("Invalid confidence_score")
        if context_profile.completeness_score < 0.0 or context_profile.completeness_score > 1.0:
            issues.append("Invalid completeness_score")
        if context_profile.clarity_score < 0.0 or context_profile.clarity_score > 1.0:
            issues.append("Invalid clarity_score")
        
        # Check performance requirements
        if context_profile.performance_requirements:
            for req, value in context_profile.performance_requirements.items():
                if not isinstance(value, int) or value < 0:
                    issues.append(f"Invalid performance requirement: {req}")
        
        is_valid = len(issues) == 0
        return is_valid, issues

class ContextAnalysisEngine:
    """
    Main context analysis engine.
    
    SpecBlock:
    - responsibility: "Analyze current context and generate context profiles"
    - must_never: "Exceed 100ms response time", "Make assumptions without evidence"
    - performance_budget: "50ms average, 100ms maximum"
    - security_level: "high"
    """
    
    def __init__(self):
        self.parser = ContextParser()
        self.classifier = TaskClassifier()
        self.intent_inferencer = IntentInferencer()
        self.resource_assessor = ResourceAssessor()
        self.validator = ContextValidator()
    
    def analyze_context(self, user_input: str, environment: Dict[str, Any]) -> ContextProfile:
        """Analyze context and generate context profile."""
        start_time = time.time()
        
        # Parse user input
        parsed_input = self.parser.parse_user_input(user_input)
        
        # Parse environment data
        parsed_environment = self.parser.parse_environment_data(environment)
        
        # Classify task
        task_type, complexity = self.classifier.classify_task(parsed_input, parsed_environment)
        
        # Infer intent
        intent = self.intent_inferencer.infer_intent(parsed_input, task_type)
        
        # Assess resources
        resources = self.resource_assessor.assess_resources(parsed_environment)
        
        # Determine context type
        context_type = self._determine_context_type(task_type, intent)
        
        # Determine complexity level
        complexity_level = self._determine_complexity_level(complexity)
        
        # Generate tool requirements
        required_capabilities = self._generate_required_capabilities(task_type, intent)
        preferred_categories = self._generate_preferred_categories(task_type, context_type)
        performance_requirements = self._generate_performance_requirements(complexity, resources)
        security_requirements = self._generate_security_requirements(task_type, resources)
        
        # Calculate quality scores
        confidence_score = self._calculate_confidence_score(parsed_input, task_type, intent)
        completeness_score = self._calculate_completeness_score(parsed_input, parsed_environment)
        clarity_score = self._calculate_clarity_score(parsed_input)
        
        # Create context profile
        context_profile = ContextProfile(
            context_id=f"ctx_{int(time.time() * 1000)}",
            timestamp=time.time(),
            context_type=context_type,
            complexity=complexity_level,
            task_classification=task_type,
            intent_inference=intent,
            resource_requirements=resources,
            constraints=resources.get('constraints', []),
            required_capabilities=required_capabilities,
            preferred_categories=preferred_categories,
            performance_requirements=performance_requirements,
            security_requirements=security_requirements,
            confidence_score=confidence_score,
            completeness_score=completeness_score,
            clarity_score=clarity_score,
            analysis_duration_ms=(time.time() - start_time) * 1000
        )
        
        # Validate context profile
        is_valid, issues = self.validator.validate_context(context_profile)
        if not is_valid:
            raise ValueError(f"Invalid context profile: {issues}")
        
        return context_profile
    
    def _determine_context_type(self, task_type: str, intent: str) -> ContextType:
        """Determine context type from task type and intent."""
        type_mapping = {
            'memory_operation': ContextType.MEMORY_OPERATION,
            'planning': ContextType.PLANNING,
            'tracking': ContextType.TRACKING,
            'synthesis': ContextType.SYNTHESIS,
            'safety': ContextType.SAFETY,
            'monitor': ContextType.MONITORING,
            'timeline': ContextType.TIMELINE,
            'learning': ContextType.LEARNING,
            'collaboration': ContextType.COLLABORATION,
            'autonomous': ContextType.AUTONOMOUS,
            'research': ContextType.RESEARCH,
            'development': ContextType.DEVELOPMENT
        }
        return type_mapping.get(task_type, ContextType.DEVELOPMENT)
    
    def _determine_complexity_level(self, complexity: float) -> ComplexityLevel:
        """Determine complexity level from complexity score."""
        if complexity <= 0.2:
            return ComplexityLevel.TRIVIAL
        elif complexity <= 0.4:
            return ComplexityLevel.LOW
        elif complexity <= 0.6:
            return ComplexityLevel.MEDIUM
        elif complexity <= 0.8:
            return ComplexityLevel.HIGH
        else:
            return ComplexityLevel.CRITICAL
    
    def _generate_required_capabilities(self, task_type: str, intent: str) -> List[str]:
        """Generate required capabilities based on task type and intent."""
        capabilities = []
        
        if task_type == 'memory_operation':
            if intent in ['store_memory', 'create']:
                capabilities.extend(['memory_storage', 'data_persistence'])
            elif intent in ['retrieve_memory', 'learn']:
                capabilities.extend(['memory_retrieval', 'semantic_search'])
        
        elif task_type == 'planning':
            capabilities.extend(['planning', 'orchestration'])
        
        elif task_type == 'tracking':
            capabilities.extend(['tracking', 'monitoring', 'provenance'])
        
        elif task_type == 'synthesis':
            capabilities.extend(['knowledge_synthesis', 'pattern_recognition'])
        
        elif task_type == 'safety':
            capabilities.extend(['invariant_checking', 'integrity_verification'])
        
        return capabilities
    
    def _generate_preferred_categories(self, task_type: str, context_type: ContextType) -> List[str]:
        """Generate preferred tool categories based on task type and context."""
        categories = []
        
        if task_type == 'memory_operation':
            categories.append('core_aimos')
        elif task_type == 'planning':
            categories.append('core_aimos')
        elif task_type == 'tracking':
            categories.extend(['core_aimos', 'timeline'])
        elif task_type == 'synthesis':
            categories.append('core_aimos')
        elif task_type == 'safety':
            categories.append('scor')
        elif task_type == 'monitoring':
            categories.extend(['observability', 'performance_monitor'])
        
        return categories
    
    def _generate_performance_requirements(self, complexity: float, resources: Dict[str, Any]) -> Dict[str, int]:
        """Generate performance requirements based on complexity and resources."""
        requirements = {}
        
        # Base performance requirements
        requirements['max_response_time_ms'] = int(100 + complexity * 200)
        requirements['max_memory_mb'] = int(50 + complexity * 100)
        requirements['max_cpu_percent'] = int(20 + complexity * 30)
        
        # Adjust based on available resources
        if resources.get('memory_available', 1000) < 500:
            requirements['max_memory_mb'] = min(requirements['max_memory_mb'], 50)
        
        if resources.get('cpu_available', 100) < 50:
            requirements['max_cpu_percent'] = min(requirements['max_cpu_percent'], 30)
        
        return requirements
    
    def _generate_security_requirements(self, task_type: str, resources: Dict[str, Any]) -> str:
        """Generate security requirements based on task type and resources."""
        if task_type == 'safety' or resources.get('security_level') == 'critical':
            return 'critical'
        elif task_type in ['memory_operation', 'planning', 'tracking']:
            return 'high'
        else:
            return 'medium'
    
    def _calculate_confidence_score(self, parsed_input: Dict[str, Any], task_type: str, intent: str) -> float:
        """Calculate confidence score for the analysis."""
        confidence = 0.5  # Base confidence
        
        # Increase confidence based on pattern matches
        pattern_count = len(parsed_input.get('detected_patterns', []))
        confidence += pattern_count * 0.1
        
        # Increase confidence based on keyword matches
        keyword_count = len(parsed_input.get('keywords', []))
        confidence += min(keyword_count * 0.02, 0.2)
        
        # Increase confidence based on intent clarity
        if intent != 'general':
            confidence += 0.1
        
        # Increase confidence based on task type clarity
        if task_type != 'general':
            confidence += 0.1
        
        return min(confidence, 1.0)
    
    def _calculate_completeness_score(self, parsed_input: Dict[str, Any], parsed_environment: Dict[str, Any]) -> float:
        """Calculate completeness score for the analysis."""
        completeness = 0.0
        
        # Check input completeness
        if parsed_input.get('raw_input'):
            completeness += 0.3
        if parsed_input.get('detected_patterns'):
            completeness += 0.2
        if parsed_input.get('keywords'):
            completeness += 0.2
        if parsed_input.get('intent_indicators'):
            completeness += 0.1
        
        # Check environment completeness
        if parsed_environment.get('session_info'):
            completeness += 0.1
        if parsed_environment.get('system_state'):
            completeness += 0.1
        
        return min(completeness, 1.0)
    
    def _calculate_clarity_score(self, parsed_input: Dict[str, Any]) -> float:
        """Calculate clarity score for the analysis."""
        clarity = 0.5  # Base clarity
        
        # Increase clarity based on input length (up to a point)
        input_length = len(parsed_input.get('raw_input', ''))
        if 50 <= input_length <= 500:
            clarity += 0.2
        elif input_length > 500:
            clarity += 0.1
        
        # Increase clarity based on pattern matches
        pattern_count = len(parsed_input.get('detected_patterns', []))
        clarity += min(pattern_count * 0.1, 0.3)
        
        return min(clarity, 1.0)

if __name__ == "__main__":
    # Test the context analysis engine
    engine = ContextAnalysisEngine()
    
    # Test context analysis
    user_input = "I need to store this important information in memory and then create a plan for implementing the daemon system"
    environment = {
        'session_info': {'user_id': 'test_user', 'session_id': 'test_session'},
        'system_state': {'memory_available': 1000, 'cpu_available': 80},
        'constraints': ['40_tool_limit', 'performance_critical']
    }
    
    try:
        profile = engine.analyze_context(user_input, environment)
        print(f"Context Analysis Complete:")
        print(f"  Context ID: {profile.context_id}")
        print(f"  Context Type: {profile.context_type.value}")
        print(f"  Complexity: {profile.complexity.value}")
        print(f"  Task Classification: {profile.task_classification}")
        print(f"  Intent: {profile.intent_inference}")
        print(f"  Required Capabilities: {profile.required_capabilities}")
        print(f"  Confidence Score: {profile.confidence_score:.2f}")
        print(f"  Analysis Duration: {profile.analysis_duration_ms:.2f}ms")
    except Exception as e:
        print(f"Error in context analysis: {e}")
