import * as vscode from 'vscode';
import { DaemonClient, ChangeProposal } from './daemonClient';

export class ChangeProposalProvider {
    private daemonClient: DaemonClient;

    constructor(daemonClient: DaemonClient) {
        this.daemonClient = daemonClient;
    }

    async showProposal(nodeId: string) {
        try {
            const proposal = await this.daemonClient.proposeChange(nodeId);
            await this.showProposalModal(nodeId, proposal);
        } catch (error) {
            vscode.window.showErrorMessage(`Failed to load change proposal for ${nodeId}: ${error}`);
        }
    }

    private async showProposalModal(nodeId: string, proposal: ChangeProposal) {
        // Create the proposal content
        const proposalContent = this.createProposalContent(proposal);
        
        // Create a new document for the proposal
        const doc = await vscode.workspace.openTextDocument({
            content: proposalContent,
            language: 'markdown'
        });
        
        // Show the proposal in a new editor
        await vscode.window.showTextDocument(doc, { 
            viewColumn: vscode.ViewColumn.Beside,
            preview: false 
        });

        // Show the governance workflow
        await this.showGovernanceWorkflow(nodeId, proposal);
    }

    private createProposalContent(proposal: ChangeProposal): string {
        return `# Change Proposal: ${proposal.node_id}

## 🎯 Blast Radius Summary
- **Direct Affected**: ${proposal.blast_radius_summary.direct_affected} nodes
- **Indirect Affected**: ${proposal.blast_radius_summary.indirect_affected} nodes
- **Risk Score**: ${(proposal.blast_radius_summary.risk_score * 100).toFixed(1)}%
- **High Risk Areas**: ${proposal.blast_radius_summary.high_risk_areas.join(', ')}

## 📋 Affected Specifications
${proposal.affected_specs.map(spec => `
### ${spec.node_id}
- **Current Status**: ${spec.current_status}
- **Proposed Status**: ${spec.proposed_status}
- **Reason**: ${spec.reason}
`).join('\n')}

## 🔒 High Security Nodes
${proposal.high_security_nodes.map(node => `- ${node}`).join('\n')}

## ⚠️ Risk Factors
${proposal.risk_factors.map(factor => `- ${factor}`).join('\n')}

## 🛠️ Required Mitigations
${proposal.required_mitigations.map(mitigation => `- ${mitigation}`).join('\n')}

## 👥 Governance Template
- **Required Approvers**: ${proposal.governance_template.required_approvers.join(', ')}
- **Rationale Required**: ${proposal.governance_template.rationale_required ? 'Yes' : 'No'}
- **Risk Acceptance Required**: ${proposal.governance_template.risk_acceptance_required ? 'Yes' : 'No'}
- **Mitigation Plan Required**: ${proposal.governance_template.mitigation_plan_required ? 'Yes' : 'No'}

---
*This proposal was generated by Lucid Orchestrator*
`;
    }

    private async showGovernanceWorkflow(nodeId: string, proposal: ChangeProposal) {
        // Show rationale input
        const rationale = await vscode.window.showInputBox({
            prompt: 'Enter rationale for this change',
            placeHolder: 'Explain why this change is necessary and acceptable...',
            validateInput: (value) => {
                if (!value || value.trim().length < 10) {
                    return 'Rationale must be at least 10 characters long';
                }
                return null;
            }
        });

        if (!rationale) {
            vscode.window.showInformationMessage('Change proposal cancelled');
            return;
        }

        // Show risk acceptance
        const riskAcceptance = await vscode.window.showQuickPick(
            ['Accept Risk', 'Reject Change'],
            {
                placeHolder: 'Do you accept the risks associated with this change?',
                canPickMany: false
            }
        );

        if (!riskAcceptance || riskAcceptance === 'Reject Change') {
            vscode.window.showInformationMessage('Change proposal rejected');
            return;
        }

        // Show mitigation plan input
        const mitigationPlan = await vscode.window.showInputBox({
            prompt: 'Enter mitigation plan for identified risks',
            placeHolder: 'Describe how you will mitigate the identified risks...',
            validateInput: (value) => {
                if (!value || value.trim().length < 10) {
                    return 'Mitigation plan must be at least 10 characters long';
                }
                return null;
            }
        });

        if (!mitigationPlan) {
            vscode.window.showInformationMessage('Change proposal cancelled - mitigation plan required');
            return;
        }

        // Show approver selection
        const approvers = await vscode.window.showQuickPick(
            ['Tech Lead', 'Security Reviewer', 'Product Owner', 'Architect'],
            {
                placeHolder: 'Select required approvers',
                canPickMany: true
            }
        );

        if (!approvers || approvers.length === 0) {
            vscode.window.showInformationMessage('Change proposal cancelled - approvers required');
            return;
        }

        // Submit the proposal
        await this.submitProposal(nodeId, {
            rationale,
            riskAcceptance,
            mitigationPlan,
            approvers
        });
    }

    private async submitProposal(nodeId: string, governanceData: any) {
        try {
            // In a real implementation, this would send the data to the daemon
            // For now, we'll just show a success message
            vscode.window.showInformationMessage(
                `Change proposal submitted for ${nodeId} with ${governanceData.approvers.length} approvers`
            );

            // Log the governance data
            console.log('Governance Data:', {
                nodeId,
                ...governanceData,
                timestamp: new Date().toISOString()
            });

        } catch (error) {
            vscode.window.showErrorMessage(`Failed to submit proposal: ${error}`);
        }
    }
}
