// Additional Panels - Simplified implementations
import React, { useEffect } from 'react'
import { Panel } from '@/types'
import { useAIMOS } from '@/hooks/useAIMOS'
import { BasePanel } from './BasePanel'
import { useLayoutStore } from '@/store/layoutStore'

// Export new panels
export { CodingChat } from './CodingChat'
export { Terminal } from './Terminal'
export { MemoryBrowser } from './MemoryBrowser'
export { SystemMonitor } from './SystemMonitor'
export { Timeline } from './Timeline'
export { PDASPanel } from './PDASPanel'
export { AgentManagement } from './AgentManagement'
export { ProblemsPanel } from './ProblemsPanel'
export { EvolutionExplorer } from './EvolutionExplorer'
export { PlanningChat } from './PlanningChat'
export { SearchPanel } from './SearchPanel'
export { OutlinePanel } from './OutlinePanel'
export { PropertiesPanel } from './PropertiesPanel'
export { GitPanel } from './GitPanel'
export { ComponentLibrary } from './ComponentLibrary'
export { DocumentationViewer } from './DocumentationViewer'
export { UIEditor } from './UIEditor'
