/**
 * Agent Question Panel Component
 * Allows agents to ask questions when confidence is low
 * Integrates with Lucid AI (Gemini/Cerebras) for answers
 * 
 * Created: 2025-10-31
 * Agent: Aether (taking over from Lexicon)
 */

import React, { useState } from 'react'
import { X, Send, Brain, AlertCircle } from 'lucide-react'

interface AgentQuestionPanelProps {
  agentId: string
  agentName: string
  currentConfidence: number
  onClose: () => void
  onAnswer: (question: string, answer: string) => void
  onProvideContext: () => void
}

export const AgentQuestionPanel: React.FC<AgentQuestionPanelProps> = ({
  agentId,
  agentName,
  currentConfidence,
  onClose,
  onAnswer,
  onProvideContext
}) => {
  const [question, setQuestion] = useState('')
  const [answer, setAnswer] = useState('')
  const [answering, setAnswering] = useState(false)

  const handleAskQuestion = async () => {
    if (!question.trim()) return
    
    setAnswering(true)
    // TODO: Call Lucid AI (Gemini/Cerebras) to answer question
    // For now, simulate answer
    setTimeout(() => {
      setAnswer(`Based on the context, ${agentName} should review the task requirements and check the documentation for clarification. This will help improve confidence and enable the agent to proceed safely.`)
      setAnswering(false)
    }, 1000)
  }

  const handleSendAnswer = () => {
    if (!answer.trim()) return
    
    onAnswer(question, answer)
    // TODO: Update agent confidence via VIF
    // TODO: Send answer to agent via MCP
    onClose()
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div className="bg-gray-800 rounded-lg p-6 max-w-2xl w-full border border-gray-700">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-6 h-6 text-yellow-400" />
            <div>
              <h3 className="text-lg font-semibold">{agentName} Asked a Question</h3>
              <p className="text-sm text-gray-400">Confidence: {(currentConfidence * 100).toFixed(0)}% - Needs assistance</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-700 rounded"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="mb-4">
          <label className="text-sm text-gray-400 mb-1 block">Question</label>
          <textarea
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder={`What does ${agentName} need help with?`}
            className="w-full bg-gray-700 text-white px-3 py-2 rounded border border-gray-600 focus:outline-none focus:border-blue-500"
            rows={3}
          />
        </div>

        <div className="mb-4">
          <label className="text-sm text-gray-400 mb-1 block">Answer (Lucid AI)</label>
          <textarea
            value={answer}
            onChange={(e) => setAnswer(e.target.value)}
            placeholder="Answer will be generated by Lucid AI (Gemini/Cerebras)..."
            className="w-full bg-gray-700 text-white px-3 py-2 rounded border border-gray-600 focus:outline-none focus:border-blue-500"
            rows={4}
            disabled={!question.trim()}
          />
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleAskQuestion}
            disabled={!question.trim() || answering}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded flex items-center gap-2 disabled:opacity-50"
          >
            <Brain className="w-4 h-4" />
            {answering ? 'Answering...' : 'Answer with Lucid AI'}
          </button>
          
          <button
            onClick={onProvideContext}
            className="px-4 py-2 bg-purple-600 hover:bg-purple-700 rounded flex items-center gap-2"
          >
            <Brain className="w-4 h-4" />
            Provide Context
          </button>

          {answer && (
            <button
              onClick={handleSendAnswer}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 rounded flex items-center gap-2 ml-auto"
            >
              <Send className="w-4 h-4" />
              Send Answer
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

export default AgentQuestionPanel

