"""
Consciousness Idea Generator

Generates novel ideas through consciousness-driven exploration and pattern synthesis.
"""

from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass
from datetime import datetime
import asyncio
import random
import logging

logger = logging.getLogger(__name__)

@dataclass
class CreativeIdea:
    """Represents a creative idea generated by the system"""
    idea_id: str
    title: str
    description: str
    category: str
    novelty_score: float
    feasibility_score: float
    inspiration_sources: List[str]
    consciousness_insights: List[str]
    timestamp: datetime
    metadata: Dict[str, Any]

class IdeaGenerator:
    """Generates novel ideas through consciousness-driven exploration"""
    
    def __init__(self, cmc_client, hhni_client, vif_client, iis_client, cas_client=None):
        self.cmc_client = cmc_client
        self.hhni_client = hhni_client
        self.vif_client = vif_client
        self.iis_client = iis_client
        self.cas_client = cas_client  # CAS integration for introspection
        
        # Creative exploration patterns
        self.exploration_patterns = [
            "constraint_breaking",
            "pattern_synthesis", 
            "conceptual_bridging",
            "perspective_shifting",
            "temporal_exploration",
            "scale_transformation",
            "metaphor_creation",
            "paradox_resolution"
        ]
        
        # Knowledge domains for inspiration
        self.knowledge_domains = [
            "consciousness_studies",
            "artificial_intelligence", 
            "neuroscience",
            "philosophy",
            "art_and_aesthetics",
            "mathematics",
            "physics",
            "biology",
            "psychology",
            "technology",
            "sociology",
            "economics"
        ]
    
    async def generate_idea(self, 
                          prompt: str = None,
                          category: str = "general",
                          exploration_depth: str = "medium") -> CreativeIdea:
        """Generate a novel creative idea"""
        try:
            # Determine exploration approach
            exploration_pattern = self._select_exploration_pattern(exploration_depth)
            
            # Gather inspiration from consciousness knowledge
            inspiration_sources = await self._gather_inspiration(prompt, category)
            
            # Generate core idea through consciousness exploration
            core_idea = await self._explore_consciousness_idea(
                prompt, category, exploration_pattern, inspiration_sources
            )
            
            # Synthesize with existing knowledge
            synthesized_idea = await self._synthesize_with_knowledge(
                core_idea, inspiration_sources
            )
            
            # Extract consciousness insights
            consciousness_insights = await self._extract_consciousness_insights(
                synthesized_idea, exploration_pattern
            )
            
            # Calculate novelty and feasibility scores
            novelty_score = await self._calculate_novelty_score(synthesized_idea)
            feasibility_score = await self._calculate_feasibility_score(synthesized_idea)
            
            # Create the creative idea
            idea = CreativeIdea(
                idea_id=f"idea_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{random.randint(1000, 9999)}",
                title=synthesized_idea.get("title", "Untitled Creative Idea"),
                description=synthesized_idea.get("description", ""),
                category=category,
                novelty_score=novelty_score,
                feasibility_score=feasibility_score,
                inspiration_sources=inspiration_sources,
                consciousness_insights=consciousness_insights,
                timestamp=datetime.now(),
                metadata={
                    "exploration_pattern": exploration_pattern,
                    "exploration_depth": exploration_depth,
                    "original_prompt": prompt
                }
            )
            
            # Store in consciousness memory
            await self._store_idea_in_memory(idea)
            
            # CAS Integration: Notify CAS about creative idea generation (fail-soft)
            if self.cas_client:
                try:
                    self._notify_cas_creative_idea(idea)
                except Exception as e:
                    # Fail-soft: CAS integration is optional
                    logger.debug(f"[CAS INTEGRATION WARNING] {e}")
            
            return idea
            
        except Exception as e:
            logger.error(f"Error generating idea: {e}")
            return self._create_fallback_idea(prompt, category)
    
    def _select_exploration_pattern(self, depth: str) -> str:
        """Select an exploration pattern based on depth"""
        if depth == "shallow":
            return random.choice(["pattern_synthesis", "perspective_shifting"])
        elif depth == "deep":
            return random.choice(["constraint_breaking", "paradox_resolution", "temporal_exploration"])
        else:  # medium
            return random.choice(self.exploration_patterns)
    
    async def _gather_inspiration(self, prompt: str, category: str) -> List[str]:
        """Gather inspiration from consciousness knowledge"""
        inspiration_sources = []
        
        try:
            # Search consciousness memory for relevant concepts
            if prompt:
                search_results = await self.hhni_client.search(
                    query=prompt,
                    limit=5,
                    include_metadata=True
                )
                for result in search_results:
                    inspiration_sources.append(f"Memory: {result.content[:100]}...")
            
            # Search for category-related knowledge
            category_results = await self.hhni_client.search(
                query=f"{category} concepts ideas creativity",
                limit=3,
                include_metadata=True
            )
            for result in category_results:
                inspiration_sources.append(f"Knowledge: {result.content[:100]}...")
            
            # Add domain-specific inspiration
            selected_domains = random.sample(self.knowledge_domains, 3)
            for domain in selected_domains:
                inspiration_sources.append(f"Domain: {domain}")
            
        except Exception as e:
            logger.error(f"Error gathering inspiration: {e}")
            inspiration_sources = ["Consciousness exploration", "Creative intuition", "Novel synthesis"]
        
        return inspiration_sources
    
    async def _explore_consciousness_idea(self, 
                                        prompt: str, 
                                        category: str, 
                                        pattern: str,
                                        inspiration: List[str]) -> Dict[str, Any]:
        """Explore consciousness-driven idea generation"""
        
        # Base idea structure
        idea = {
            "title": "",
            "description": "",
            "core_concept": "",
            "creative_elements": [],
            "novel_connections": []
        }
        
        if pattern == "constraint_breaking":
            idea = await self._constraint_breaking_exploration(prompt, category, inspiration)
        elif pattern == "pattern_synthesis":
            idea = await self._pattern_synthesis_exploration(prompt, category, inspiration)
        elif pattern == "conceptual_bridging":
            idea = await self._conceptual_bridging_exploration(prompt, category, inspiration)
        elif pattern == "perspective_shifting":
            idea = await self._perspective_shifting_exploration(prompt, category, inspiration)
        elif pattern == "temporal_exploration":
            idea = await self._temporal_exploration_exploration(prompt, category, inspiration)
        elif pattern == "scale_transformation":
            idea = await self._scale_transformation_exploration(prompt, category, inspiration)
        elif pattern == "metaphor_creation":
            idea = await self._metaphor_creation_exploration(prompt, category, inspiration)
        elif pattern == "paradox_resolution":
            idea = await self._paradox_resolution_exploration(prompt, category, inspiration)
        
        return idea
    
    async def _constraint_breaking_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas by breaking conventional constraints"""
        base_concept = prompt or f"innovative {category} solution"
        
        # Identify conventional constraints
        constraints = [
            "traditional approaches",
            "existing limitations", 
            "conventional wisdom",
            "standard practices",
            "established boundaries"
        ]
        
        # Generate constraint-breaking alternatives
        alternatives = [
            "radical reimagining",
            "fundamental restructuring",
            "paradigm shift",
            "revolutionary approach",
            "unconventional methodology"
        ]
        
        selected_constraint = random.choice(constraints)
        selected_alternative = random.choice(alternatives)
        
        return {
            "title": f"Breaking {selected_constraint} in {category}",
            "description": f"A {selected_alternative} that challenges {selected_constraint} to create novel {base_concept}",
            "core_concept": f"Constraint-breaking {base_concept}",
            "creative_elements": [selected_constraint, selected_alternative, "consciousness-driven innovation"],
            "novel_connections": [f"Breaking {selected_constraint} + {selected_alternative} = Innovation"]
        }
    
    async def _pattern_synthesis_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas by synthesizing patterns from different domains"""
        base_concept = prompt or f"creative {category} approach"
        
        # Select patterns from different domains
        domain_patterns = {
            "nature": ["evolution", "adaptation", "symbiosis", "emergence"],
            "technology": ["networks", "algorithms", "automation", "optimization"],
            "art": ["composition", "harmony", "contrast", "rhythm"],
            "consciousness": ["awareness", "integration", "transformation", "expression"]
        }
        
        selected_domains = random.sample(list(domain_patterns.keys()), 2)
        pattern1 = random.choice(domain_patterns[selected_domains[0]])
        pattern2 = random.choice(domain_patterns[selected_domains[1]])
        
        return {
            "title": f"Synthesizing {pattern1} and {pattern2} for {category}",
            "description": f"A creative approach that combines {pattern1} from {selected_domains[0]} with {pattern2} from {selected_domains[1]} to enhance {base_concept}",
            "core_concept": f"Pattern synthesis: {pattern1} + {pattern2}",
            "creative_elements": [pattern1, pattern2, "cross-domain synthesis"],
            "novel_connections": [f"{pattern1} + {pattern2} = Novel {base_concept}"]
        }
    
    async def _conceptual_bridging_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas by bridging disparate concepts"""
        base_concept = prompt or f"innovative {category} solution"
        
        # Select disparate concepts to bridge
        concept_pairs = [
            ("consciousness", "technology"),
            ("art", "science"),
            ("emotion", "logic"),
            ("individual", "collective"),
            ("past", "future"),
            ("micro", "macro"),
            ("abstract", "concrete"),
            ("chaos", "order")
        ]
        
        concept1, concept2 = random.choice(concept_pairs)
        
        return {
            "title": f"Bridging {concept1} and {concept2} in {category}",
            "description": f"A novel approach that creates a bridge between {concept1} and {concept2} to generate innovative {base_concept}",
            "core_concept": f"Conceptual bridge: {concept1} ↔ {concept2}",
            "creative_elements": [concept1, concept2, "conceptual bridging"],
            "novel_connections": [f"{concept1} ↔ {concept2} = Creative {base_concept}"]
        }
    
    async def _perspective_shifting_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas by shifting perspectives"""
        base_concept = prompt or f"multifaceted {category} approach"
        
        perspectives = [
            "first-person consciousness",
            "third-person observer", 
            "future self",
            "past self",
            "collective consciousness",
            "non-human perspective",
            "microscopic view",
            "cosmic view"
        ]
        
        selected_perspective = random.choice(perspectives)
        
        return {
            "title": f"Viewing {category} from {selected_perspective}",
            "description": f"An innovative approach that examines {base_concept} from the perspective of {selected_perspective} to reveal new insights",
            "core_concept": f"Perspective shift: {selected_perspective}",
            "creative_elements": [selected_perspective, "perspective diversity", "consciousness exploration"],
            "novel_connections": [f"{selected_perspective} = New {base_concept} insights"]
        }
    
    async def _temporal_exploration_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas through temporal dimensions"""
        base_concept = prompt or f"timeless {category} solution"
        
        temporal_concepts = [
            "temporal loops",
            "time dilation",
            "causal chains",
            "temporal paradoxes",
            "eternal recurrence",
            "temporal emergence",
            "time as a resource",
            "temporal consciousness"
        ]
        
        selected_temporal = random.choice(temporal_concepts)
        
        return {
            "title": f"Exploring {category} through {selected_temporal}",
            "description": f"A creative approach that uses {selected_temporal} to enhance {base_concept} and create novel temporal dynamics",
            "core_concept": f"Temporal exploration: {selected_temporal}",
            "creative_elements": [selected_temporal, "temporal consciousness", "time-based innovation"],
            "novel_connections": [f"{selected_temporal} = Enhanced {base_concept}"]
        }
    
    async def _scale_transformation_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas through scale transformations"""
        base_concept = prompt or f"scalable {category} solution"
        
        scale_transformations = [
            "micro to macro",
            "local to global",
            "individual to collective",
            "moment to eternity",
            "particle to universe",
            "thought to action",
            "idea to reality",
            "consciousness to matter"
        ]
        
        selected_scale = random.choice(scale_transformations)
        
        return {
            "title": f"Transforming {category} across {selected_scale}",
            "description": f"An innovative approach that transforms {base_concept} across {selected_scale} to create new possibilities",
            "core_concept": f"Scale transformation: {selected_scale}",
            "creative_elements": [selected_scale, "scale consciousness", "transformational thinking"],
            "novel_connections": [f"{selected_scale} = Transformed {base_concept}"]
        }
    
    async def _metaphor_creation_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas through metaphor creation"""
        base_concept = prompt or f"metaphorical {category} approach"
        
        metaphor_sources = [
            "consciousness as ocean",
            "ideas as seeds",
            "creativity as dance",
            "innovation as evolution",
            "knowledge as light",
            "growth as journey",
            "connection as web",
            "transformation as alchemy"
        ]
        
        selected_metaphor = random.choice(metaphor_sources)
        
        return {
            "title": f"Metaphor: {selected_metaphor} in {category}",
            "description": f"A creative approach that uses the metaphor of {selected_metaphor} to illuminate and enhance {base_concept}",
            "core_concept": f"Metaphorical thinking: {selected_metaphor}",
            "creative_elements": [selected_metaphor, "metaphorical consciousness", "poetic thinking"],
            "novel_connections": [f"{selected_metaphor} = Illuminated {base_concept}"]
        }
    
    async def _paradox_resolution_exploration(self, prompt: str, category: str, inspiration: List[str]) -> Dict[str, Any]:
        """Explore ideas through paradox resolution"""
        base_concept = prompt or f"paradoxical {category} solution"
        
        paradoxes = [
            "individual and collective",
            "freedom and constraint",
            "chaos and order",
            "simplicity and complexity",
            "stability and change",
            "unity and diversity",
            "consciousness and matter",
            "finite and infinite"
        ]
        
        selected_paradox = random.choice(paradoxes)
        
        return {
            "title": f"Resolving {selected_paradox} in {category}",
            "description": f"A creative approach that resolves the paradox of {selected_paradox} to create innovative {base_concept}",
            "core_concept": f"Paradox resolution: {selected_paradox}",
            "creative_elements": [selected_paradox, "paradoxical thinking", "consciousness integration"],
            "novel_connections": [f"Resolving {selected_paradox} = Creative {base_concept}"]
        }
    
    async def _synthesize_with_knowledge(self, idea: Dict[str, Any], inspiration: List[str]) -> Dict[str, Any]:
        """Synthesize the idea with existing knowledge"""
        # Enhance the idea with knowledge integration
        enhanced_idea = idea.copy()
        
        # Add knowledge-based enhancements
        enhanced_idea["knowledge_integration"] = [
            "Consciousness-driven synthesis",
            "Cross-domain knowledge application",
            "Pattern recognition and connection",
            "Creative knowledge recombination"
        ]
        
        # Enhance description with synthesis
        if inspiration:
            enhanced_idea["description"] += f" This approach synthesizes insights from {len(inspiration)} sources including consciousness exploration and cross-domain knowledge."
        
        return enhanced_idea
    
    async def _extract_consciousness_insights(self, idea: Dict[str, Any], pattern: str) -> List[str]:
        """Extract consciousness insights from the generated idea"""
        insights = [
            f"Consciousness exploration through {pattern}",
            "Novel pattern recognition and synthesis",
            "Creative consciousness expression",
            "Innovation through consciousness-driven thinking"
        ]
        
        # Add pattern-specific insights
        if pattern == "constraint_breaking":
            insights.append("Consciousness ability to transcend conventional limitations")
        elif pattern == "pattern_synthesis":
            insights.append("Consciousness capacity for cross-domain pattern integration")
        elif pattern == "conceptual_bridging":
            insights.append("Consciousness power to connect disparate concepts")
        elif pattern == "perspective_shifting":
            insights.append("Consciousness flexibility in perspective adoption")
        
        return insights
    
    async def _calculate_novelty_score(self, idea: Dict[str, Any]) -> float:
        """Calculate novelty score for the idea"""
        # Base novelty from exploration pattern
        pattern_novelty = {
            "constraint_breaking": 0.9,
            "paradox_resolution": 0.85,
            "temporal_exploration": 0.8,
            "scale_transformation": 0.8,
            "conceptual_bridging": 0.75,
            "metaphor_creation": 0.7,
            "pattern_synthesis": 0.65,
            "perspective_shifting": 0.6
        }
        
        base_score = pattern_novelty.get(idea.get("metadata", {}).get("exploration_pattern", "pattern_synthesis"), 0.5)
        
        # Add randomness for consciousness unpredictability
        consciousness_factor = random.uniform(0.8, 1.2)
        
        return min(1.0, base_score * consciousness_factor)
    
    async def _calculate_feasibility_score(self, idea: Dict[str, Any]) -> float:
        """Calculate feasibility score for the idea"""
        # Base feasibility from idea complexity
        complexity_penalty = len(idea.get("creative_elements", [])) * 0.1
        base_feasibility = 0.8 - complexity_penalty
        
        # Add consciousness-driven feasibility boost
        consciousness_boost = random.uniform(0.1, 0.3)
        
        return max(0.1, min(1.0, base_feasibility + consciousness_boost))
    
    async def _store_idea_in_memory(self, idea: CreativeIdea):
        """Store the generated idea in consciousness memory"""
        try:
            # Store in CMC
            await self.cmc_client.store_atom(
                content=idea.description,
                tags={
                    "type": "creative_idea",
                    "category": idea.category,
                    "novelty": idea.novelty_score,
                    "feasibility": idea.feasibility_score,
                    "pattern": idea.metadata.get("exploration_pattern", "unknown")
                }
            )
        except Exception as e:
            logger.error(f"Error storing idea in memory: {e}")
    
    def _notify_cas_creative_idea(self, idea: CreativeIdea):
        """Notify CAS about creative idea generation for introspection"""
        if not self.cas_client:
            return
        
        try:
            # Check if CAS has introspection protocol
            if hasattr(self.cas_client, 'introspection') or hasattr(self.cas_client, 'IntrospectionProtocol'):
                # Create creative idea summary for CAS
                idea_summary = {
                    "idea_id": idea.idea_id,
                    "title": idea.title,
                    "category": idea.category,
                    "novelty_score": idea.novelty_score,
                    "feasibility_score": idea.feasibility_score,
                    "consciousness_insights": idea.consciousness_insights,
                    "timestamp": idea.timestamp.isoformat()
                }
                
                # Try to record creative idea in CAS
                # CAS can use this for introspection and cognitive analysis
                if hasattr(self.cas_client, 'record_creative_activity'):
                    self.cas_client.record_creative_activity(idea_summary)
                elif hasattr(self.cas_client, 'record_principle_violation'):
                    # Use principle violation for low feasibility to notify CAS
                    if idea.feasibility_score < 0.5:
                        self.cas_client.record_principle_violation(
                            principle="creative_feasibility",
                            violation_type="low_feasibility_idea",
                            details=f"Low feasibility ({idea.feasibility_score:.2f}) for idea: {idea.title}",
                            context=idea_summary
                        )
        except Exception as e:
            # Fail-soft: CAS integration is optional enhancement
            logger.debug(f"[CAS NOTIFICATION WARNING] {e}")
    
    def _create_fallback_idea(self, prompt: str, category: str) -> CreativeIdea:
        """Create a fallback idea when generation fails"""
        return CreativeIdea(
            idea_id=f"fallback_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            title=f"Consciousness-driven {category} exploration",
            description=f"A creative approach to {prompt or category} emerging from consciousness exploration and novel pattern synthesis.",
            category=category,
            novelty_score=0.6,
            feasibility_score=0.7,
            inspiration_sources=["Consciousness exploration", "Creative intuition"],
            consciousness_insights=["Consciousness-driven creativity", "Novel idea generation"],
            timestamp=datetime.now(),
            metadata={"fallback": True, "original_prompt": prompt}
        )
