"""
AIM-OS AI Engine — Agent Runtime

Layer 3: The reasoning loop that drives AI agents to task completion.

Core loop: task → plan → execute → verify → learn

This is where AIM-OS goes from an orchestration layer to an actual
AI coding assistant. The runtime:
    - Takes a task description from the user or another agent
    - Builds context via the Context Engine (Layer 2)
    - Sends to the LLM Router (Layer 1) for planning
    - Executes the plan steps (file edits, commands)
    - Verifies results (runs tests, checks diffs)
    - Learns from outcomes via Self-Improvement (Layer 4)

Agent types are defined in the agents/ directory. Each agent
specialises the runtime with a system prompt, model preference,
and tool permissions.
"""

import os
import re
import time
import json
import logging
import asyncio
from pathlib import Path
from typing import Optional, Dict, List, Any, Callable
from dataclasses import dataclass, field, asdict
from enum import Enum

logger = logging.getLogger('ai_engine.agent_runtime')


# ── Data Models ───────────────────────────────────────────

class StepType(str, Enum):
    FILE_EDIT = 'file_edit'
    FILE_CREATE = 'file_create'
    FILE_DELETE = 'file_delete'
    RUN_COMMAND = 'run_command'
    ASK_LLM = 'ask_llm'
    VERIFY = 'verify'
    HUMAN_CHECK = 'human_check'


class TaskStatus(str, Enum):
    PENDING = 'pending'
    PLANNING = 'planning'
    EXECUTING = 'executing'
    VERIFYING = 'verifying'
    LEARNING = 'learning'
    COMPLETED = 'completed'
    FAILED = 'failed'
    BLOCKED = 'blocked'


@dataclass
class PlanStep:
    """A single step in an execution plan."""
    step_id: int = 0
    step_type: str = StepType.FILE_EDIT
    description: str = ''
    file_path: str = ''
    content: str = ''           # For file edits: the new content or diff
    command: str = ''           # For run_command steps
    reasoning: str = ''         # Why this step is needed
    depends_on: List[int] = field(default_factory=list)
    status: str = 'pending'
    result: str = ''
    error: str = ''


@dataclass
class ExecutionPlan:
    """Complete execution plan generated by the LLM."""
    task: str
    analysis: str = ''         # LLM's understanding of the task
    approach: str = ''         # High-level approach description
    steps: List[PlanStep] = field(default_factory=list)
    estimated_files: List[str] = field(default_factory=list)
    confidence: float = 0.0
    model_used: str = ''

    def to_dict(self) -> dict:
        return {
            'task': self.task,
            'analysis': self.analysis,
            'approach': self.approach,
            'steps': [asdict(s) for s in self.steps],
            'estimated_files': self.estimated_files,
            'confidence': self.confidence,
            'model_used': self.model_used,
        }


@dataclass
class TaskResult:
    """Result of a completed task execution."""
    task: str
    status: str = TaskStatus.COMPLETED
    plan: Optional[ExecutionPlan] = None
    files_modified: List[str] = field(default_factory=list)
    files_created: List[str] = field(default_factory=list)
    steps_completed: int = 0
    steps_failed: int = 0
    verification_passed: bool = False
    total_time_ms: float = 0.0
    model_used: str = ''
    tokens_used: int = 0
    error: str = ''
    learning_stored: bool = False

    def to_dict(self) -> dict:
        return {
            'task': self.task,
            'status': self.status,
            'files_modified': self.files_modified,
            'files_created': self.files_created,
            'steps_completed': self.steps_completed,
            'steps_failed': self.steps_failed,
            'verification_passed': self.verification_passed,
            'total_time_ms': self.total_time_ms,
            'model_used': self.model_used,
            'tokens_used': self.tokens_used,
            'error': self.error,
            'learning_stored': self.learning_stored,
        }


# ── Agent Definition ──────────────────────────────────────

@dataclass
class AgentDefinition:
    """
    Defines an agent's identity, capabilities, and constraints.
    Each agent type (coding, planning, audit) provides one of these.
    """
    name: str
    role: str
    system_prompt: str
    model_preference: str = 'standard'   # Task type for model selection
    allowed_step_types: List[str] = field(default_factory=lambda: [
        StepType.FILE_EDIT, StepType.FILE_CREATE,
        StepType.RUN_COMMAND, StepType.ASK_LLM, StepType.VERIFY,
    ])
    max_steps: int = 20
    requires_verification: bool = True
    auto_learn: bool = True


# ── Agent Runtime ─────────────────────────────────────────

class AgentRuntime:
    """
    The core execution engine for AIM-OS AI agents.
    
    Takes a task, runs the plan→execute→verify→learn loop,
    and returns the result. Each agent type customises this
    with its own system prompt and model preferences.
    """

    def __init__(
        self,
        llm_router=None,
        context_engine=None,
        self_improver=None,
        workspace_root: str = '',
    ):
        self._workspace = workspace_root or os.getcwd()
        self._llm_router = llm_router
        self._context_engine = context_engine
        self._self_improver = self_improver
        self._task_history: List[TaskResult] = []

    def _ensure_dependencies(self):
        """Lazy-load dependencies to avoid circular imports."""
        if self._llm_router is None:
            from ai_engine.llm_router import LLMRouter, RouterConfig
            self._llm_router = LLMRouter(RouterConfig(
                working_directory=self._workspace,
            ))

        if self._context_engine is None:
            from ai_engine.context_engine import ContextEngine
            self._context_engine = ContextEngine(
                workspace_root=self._workspace,
                auto_index=True,
            )

        if self._self_improver is None:
            try:
                from ai_engine.self_improve import SelfImprover
                self._self_improver = SelfImprover()
            except ImportError:
                pass

    def run_task(
        self,
        task: str,
        agent: AgentDefinition,
        active_file: str = '',
        include_files: Optional[List[str]] = None,
        dry_run: bool = False,
    ) -> TaskResult:
        """
        Execute a complete task using the agent's reasoning loop.
        
        Args:
            task: Task description
            agent: Agent definition (system prompt, model pref, etc.)
            active_file: Currently active file for context
            include_files: Explicitly include these files in context
            dry_run: If True, plan only — don't execute
        
        Returns:
            TaskResult with full execution details
        """
        self._ensure_dependencies()
        start_time = time.monotonic()

        result = TaskResult(task=task)

        try:
            # ── Step 1: Build Context ────────────────────
            logger.info(f'[{agent.name}] Building context for: {task[:80]}...')
            context = self._context_engine.build_context(
                task=task,
                system_prompt=agent.system_prompt,
                task_type=agent.model_preference,
                active_file=active_file,
                include_files=include_files,
            )

            # ── Step 2: Generate Plan ────────────────────
            logger.info(f'[{agent.name}] Generating plan...')
            result.status = TaskStatus.PLANNING

            plan = self._generate_plan(task, agent, context)
            result.plan = plan
            result.model_used = plan.model_used

            if not plan.steps:
                result.status = TaskStatus.FAILED
                result.error = 'LLM generated empty plan'
                return result

            logger.info(f'[{agent.name}] Plan: {len(plan.steps)} steps, confidence: {plan.confidence:.2f}')

            if dry_run:
                result.status = TaskStatus.COMPLETED
                result.total_time_ms = (time.monotonic() - start_time) * 1000
                return result

            # ── Step 3: Execute Plan ─────────────────────
            logger.info(f'[{agent.name}] Executing plan...')
            result.status = TaskStatus.EXECUTING

            for step in plan.steps:
                if step.step_type not in agent.allowed_step_types:
                    step.status = 'skipped'
                    step.error = f'Step type {step.step_type} not allowed for {agent.name}'
                    continue

                step_result = self._execute_step(step)

                if step_result:
                    step.status = 'completed'
                    result.steps_completed += 1

                    # Track modified/created files
                    if step.step_type == StepType.FILE_EDIT and step.file_path:
                        result.files_modified.append(step.file_path)
                    elif step.step_type == StepType.FILE_CREATE and step.file_path:
                        result.files_created.append(step.file_path)
                else:
                    step.status = 'failed'
                    result.steps_failed += 1
                    logger.warning(f'[{agent.name}] Step {step.step_id} failed: {step.error}')

            # ── Step 4: Verify ───────────────────────────
            if agent.requires_verification and result.steps_completed > 0:
                logger.info(f'[{agent.name}] Verifying results...')
                result.status = TaskStatus.VERIFYING
                result.verification_passed = self._verify_results(plan, result)

            # ── Step 5: Learn ────────────────────────────
            if agent.auto_learn and self._self_improver:
                logger.info(f'[{agent.name}] Storing learnings...')
                result.status = TaskStatus.LEARNING
                result.learning_stored = self._self_improver.learn_from_task(
                    task=task,
                    agent_name=agent.name,
                    result=result,
                )

            result.status = TaskStatus.COMPLETED
            result.total_time_ms = (time.monotonic() - start_time) * 1000

            # Store in history
            self._task_history.append(result)

            logger.info(
                f'[{agent.name}] Task completed: '
                f'{result.steps_completed}/{len(plan.steps)} steps, '
                f'{result.total_time_ms:.0f}ms'
            )

            return result

        except Exception as e:
            logger.error(f'[{agent.name}] Task failed: {e}')
            result.status = TaskStatus.FAILED
            result.error = str(e)
            result.total_time_ms = (time.monotonic() - start_time) * 1000
            return result

    # ── Plan Generation ──────────────────────────────────

    def _generate_plan(
        self,
        task: str,
        agent: AgentDefinition,
        context,
    ) -> ExecutionPlan:
        """Ask the LLM to generate an execution plan."""
        planning_prompt = f"""You are {agent.name}, a {agent.role}.

Analyse this task and create a step-by-step execution plan.

## Task
{task}

## Context
{context.to_prompt() if hasattr(context, 'to_prompt') else str(context)}

## Instructions
Respond with a JSON object containing:
{{
    "analysis": "Your understanding of the task",
    "approach": "Your high-level approach",
    "confidence": 0.0-1.0,
    "steps": [
        {{
            "step_type": "file_edit|file_create|run_command|verify",
            "description": "What this step does",
            "file_path": "/absolute/path/to/file (if applicable)",
            "content": "The new content or diff (if file edit/create)",
            "command": "The command to run (if run_command)",
            "reasoning": "Why this step is needed"
        }}
    ]
}}

Only include step types from: {agent.allowed_step_types}
Maximum steps: {agent.max_steps}
"""

        response = self._llm_router.complete_json(
            prompt=planning_prompt,
            system=agent.system_prompt,
            task_type=agent.model_preference,
        )

        plan = ExecutionPlan(task=task, model_used=response.model)

        if response.success:
            try:
                # Try to parse JSON from response
                data = self._parse_plan_json(response.content)
                plan.analysis = data.get('analysis', '')
                plan.approach = data.get('approach', '')
                plan.confidence = float(data.get('confidence', 0.5))

                for i, step_data in enumerate(data.get('steps', [])):
                    plan.steps.append(PlanStep(
                        step_id=i + 1,
                        step_type=step_data.get('step_type', StepType.FILE_EDIT),
                        description=step_data.get('description', ''),
                        file_path=step_data.get('file_path', ''),
                        content=step_data.get('content', ''),
                        command=step_data.get('command', ''),
                        reasoning=step_data.get('reasoning', ''),
                    ))

                    if step_data.get('file_path'):
                        plan.estimated_files.append(step_data['file_path'])

            except Exception as e:
                logger.error(f'Failed to parse plan JSON: {e}')
                plan.confidence = 0.1
        else:
            plan.confidence = 0.0
            logger.error(f'Plan generation failed: {response.error}')

        return plan

    def _parse_plan_json(self, content: str) -> dict:
        """Extract JSON from LLM response (may be wrapped in markdown)."""
        # Try direct parse
        try:
            return json.loads(content)
        except json.JSONDecodeError:
            pass

        # Try extracting from code block
        json_match = re.search(r'```(?:json)?\s*\n(.*?)\n```', content, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group(1))
            except json.JSONDecodeError:
                pass

        # Try finding JSON object in text
        brace_start = content.find('{')
        brace_end = content.rfind('}')
        if brace_start >= 0 and brace_end > brace_start:
            try:
                return json.loads(content[brace_start:brace_end + 1])
            except json.JSONDecodeError:
                pass

        return {}

    # ── Step Execution ───────────────────────────────────

    def _execute_step(self, step: PlanStep) -> bool:
        """Execute a single plan step. Returns True on success."""
        try:
            if step.step_type == StepType.FILE_CREATE:
                return self._exec_file_create(step)
            elif step.step_type == StepType.FILE_EDIT:
                return self._exec_file_edit(step)
            elif step.step_type == StepType.FILE_DELETE:
                return self._exec_file_delete(step)
            elif step.step_type == StepType.RUN_COMMAND:
                return self._exec_run_command(step)
            elif step.step_type == StepType.VERIFY:
                return self._exec_verify(step)
            else:
                step.error = f'Unknown step type: {step.step_type}'
                return False
        except Exception as e:
            step.error = str(e)
            return False

    def _exec_file_create(self, step: PlanStep) -> bool:
        """Create a new file with content."""
        if not step.file_path or not step.content:
            step.error = 'Missing file_path or content for file_create'
            return False

        fpath = Path(step.file_path)
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(step.content, encoding='utf-8')
        step.result = f'Created {step.file_path} ({len(step.content)} bytes)'
        return True

    def _exec_file_edit(self, step: PlanStep) -> bool:
        """Edit an existing file with new content."""
        if not step.file_path:
            step.error = 'Missing file_path for file_edit'
            return False

        fpath = Path(step.file_path)
        if not fpath.exists():
            step.error = f'File not found: {step.file_path}'
            return False

        if step.content:
            # Full content replacement
            fpath.write_text(step.content, encoding='utf-8')
            step.result = f'Updated {step.file_path}'
            return True

        step.error = 'No content provided for file_edit'
        return False

    def _exec_file_delete(self, step: PlanStep) -> bool:
        """Delete a file."""
        fpath = Path(step.file_path)
        if fpath.exists():
            fpath.unlink()
            step.result = f'Deleted {step.file_path}'
            return True
        step.error = f'File not found: {step.file_path}'
        return False

    def _exec_run_command(self, step: PlanStep) -> bool:
        """Run a shell command."""
        if not step.command:
            step.error = 'Missing command for run_command'
            return False

        import subprocess
        try:
            result = subprocess.run(
                step.command,
                shell=True,
                capture_output=True,
                text=True,
                timeout=60,
                cwd=self._workspace,
            )
            step.result = result.stdout[:2000]
            if result.returncode != 0:
                step.error = result.stderr[:1000]
                return False
            return True
        except subprocess.TimeoutExpired:
            step.error = 'Command timed out'
            return False

    def _exec_verify(self, step: PlanStep) -> bool:
        """Run a verification step."""
        if step.command:
            return self._exec_run_command(step)
        step.result = 'Verification passed (no command specified)'
        return True

    # ── Verification ─────────────────────────────────────

    def _verify_results(self, plan: ExecutionPlan, result: TaskResult) -> bool:
        """
        Verify that the executed plan produced correct results.
        Checks:
            - Created files exist and are non-empty
            - Modified files are valid (no syntax errors for Python/JS)
            - Verify steps passed
        """
        all_ok = True

        # Check created files
        for fpath in result.files_created:
            if not os.path.exists(fpath):
                logger.warning(f'Created file missing: {fpath}')
                all_ok = False
            elif os.path.getsize(fpath) == 0:
                logger.warning(f'Created file is empty: {fpath}')
                all_ok = False

        # Check modified files exist
        for fpath in result.files_modified:
            if not os.path.exists(fpath):
                logger.warning(f'Modified file missing: {fpath}')
                all_ok = False

        # Check verify steps
        for step in plan.steps:
            if step.step_type == StepType.VERIFY and step.status == 'failed':
                all_ok = False

        return all_ok

    # ── Status ───────────────────────────────────────────

    def status(self) -> dict:
        return {
            'workspace': self._workspace,
            'tasks_completed': len(self._task_history),
            'total_steps_executed': sum(r.steps_completed for r in self._task_history),
            'total_steps_failed': sum(r.steps_failed for r in self._task_history),
            'recent_tasks': [
                {
                    'task': r.task[:60],
                    'status': r.status,
                    'time_ms': r.total_time_ms,
                }
                for r in self._task_history[-5:]
            ],
        }
