#!/usr/bin/env python3
"""
Render a deterministic Codex CLI activation prompt from repo doctrine files.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

from identity_registry import resolve_identity


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").replace("\ufeff", "").strip()


def resolve_repo_path(repo_root: Path, raw_path: str) -> Path:
    path = Path(raw_path)
    return path.resolve() if path.is_absolute() else (repo_root / path).resolve()


def render_file_block(label: str, repo_root: Path, path: Path) -> str:
    try:
        rel = path.relative_to(repo_root)
        display_path = str(rel).replace("\\", "/")
    except ValueError:
        display_path = str(path)
    body = read_text(path)
    return (
        f"## {label}\n"
        f"Path: `{display_path}`\n\n"
        "```md\n"
        f"{body}\n"
        "```\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a Codex activation prompt from repo files")
    parser.add_argument("--repo-root", default=".", help="Repository root")
    parser.add_argument("--agent", required=True, help="Agent name or callsign")
    parser.add_argument("--activation-brief", required=True, help="Activation brief path")
    parser.add_argument("--mission-packet", required=True, help="Mission packet path")
    parser.add_argument("--mcp-mode", required=True, choices=["native", "http-bridge", "degraded-no-mcp"])
    parser.add_argument("--deliverable", required=True, help="Requested deliverable path")
    parser.add_argument("--bootstrap-snapshot", help="Optional bootstrap snapshot text file path")
    parser.add_argument("--output", required=True, help="Output prompt file path")
    return parser.parse_args()


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    identity = resolve_identity(args.agent, strict=False)

    required_files = [
        ("AGENTS", resolve_repo_path(repo_root, "AGENTS.md")),
        ("STARTUP", resolve_repo_path(repo_root, ".agent/STARTUP.md")),
        ("COMMS DOCTRINE", resolve_repo_path(repo_root, ".agent/COMMS_DOCTRINE.md")),
        ("ACTIVATION BRIEF", resolve_repo_path(repo_root, args.activation_brief)),
        ("MISSION PACKET", resolve_repo_path(repo_root, args.mission_packet)),
    ]

    missing = [str(path) for _, path in required_files if not path.exists()]
    if missing:
        raise FileNotFoundError(f"Missing required file(s): {', '.join(missing)}")

    bootstrap_snapshot = ""
    if args.bootstrap_snapshot:
        snapshot_path = resolve_repo_path(repo_root, args.bootstrap_snapshot)
        if not snapshot_path.exists():
            raise FileNotFoundError(f"Bootstrap snapshot not found: {snapshot_path}")
        bootstrap_snapshot = read_text(snapshot_path)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    deliverable_path = resolve_repo_path(repo_root, args.deliverable)
    output_path = resolve_repo_path(repo_root, args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    prompt_parts = [
        f"# Codex Activation Prompt\nGenerated: {generated_at}\n",
        "You are launching an AIM-OS Codex CLI lane from a repo-first wrapper.\n",
        "## Execution Context\n"
        f"- Agent input: `{args.agent}`\n"
        f"- Canonical identity: `{identity['canonical_id']}`\n"
        f"- Route key: `{identity['route_key']}`\n"
        f"- Repo root: `{repo_root}`\n"
        f"- Requested deliverable path: `{deliverable_path}`\n"
        f"- Launcher preflight MCP mode: `{args.mcp_mode}`\n"
        f"- Activation brief: `{Path(args.activation_brief).as_posix()}`\n"
        f"- Mission packet: `{Path(args.mission_packet).as_posix()}`\n",
        "## Instructions\n"
        "- Follow the embedded doctrine files in order.\n"
        "- Treat the launcher-selected MCP mode as preflight evidence, but re-check live transport if the packet requires it.\n"
        "- Keep scope bounded to the selected packet.\n"
        "- Distinguish Codex CLI from Cursor Codex.\n"
        "- Return the final deliverable content as your last message so the launcher can write it to the requested output path.\n",
    ]

    if bootstrap_snapshot:
        prompt_parts.append(
            "## Filesystem Bootstrap Snapshot\n"
            "This was generated by `scripts/agent_comms/bootstrap_agent_session.py` before launch.\n\n"
            "```text\n"
            f"{bootstrap_snapshot}\n"
            "```\n"
        )

    prompt_parts.append("## Embedded Doctrine Files\n")
    prompt_parts.extend(render_file_block(label, repo_root, path) for label, path in required_files)

    output_path.write_text("\n".join(prompt_parts), encoding="utf-8")

    print(f"ok: {output_path}")
    print(f"agent={identity['canonical_id']}")
    print(f"route={identity['route_key']}")
    print(f"mcp_mode={args.mcp_mode}")
    print(f"deliverable={deliverable_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
